"use client";

// import { Button } from "@/components/ui/button"; // Replaced with native button to avoid build error
import jsPDF from "jspdf";

interface Props {
    estimates: any[];
    project: any;
    laborData?: any[];
    materialData?: any[];
    profile?: any;
    dependencies?: any[];
}

export default function PdfDownloadButton({ estimates, project, profile, dependencies }: Props) {

    const generatePDF = async () => {
        const doc = new jsPDF();
        let currentY = 20;

        // --- HELPER: CHECK PAGE BREAK ---
        const checkPageBreak = (y: number, heightNeeded: number) => {
            if (y + heightNeeded > 270) {
                doc.addPage();
                return 20; // Reset to top
            }
            return y;
        };

        // --- PAGE 1: COVER ---
        if (profile?.company_name) {
            doc.setFontSize(22);
            doc.setFont("helvetica", "bold");
            doc.text(profile.company_name, 14, currentY);

            doc.setFontSize(10);
            doc.setFont("helvetica", "normal");
            doc.text(profile.address_line1 || "", 14, currentY + 6);
            doc.text(profile.city || "", 14, currentY + 11);
            doc.text(profile.phone || "", 14, currentY + 16);
            doc.text(profile.email || "", 14, currentY + 21);
        } else {
            doc.setFontSize(22);
            doc.setFont("helvetica", "bold");
            doc.text("CONSTRUCTA", 14, currentY);
        }

        currentY = 60;
        doc.setFontSize(16);
        doc.setFont("helvetica", "bold");
        doc.text("PROJECT PROPOSAL", 14, currentY);

        currentY += 10;
        doc.setFontSize(12);
        doc.setFont("helvetica", "normal");
        doc.text(`Project: ${project?.name || "Untitled Project"}`, 14, currentY);
        doc.text(`Client: ${project?.client_name || "Valued Client"}`, 14, currentY + 7);
        doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, currentY + 14);

        // GRAND TOTAL
        const grandTotal = estimates.reduce((sum, est) => {
            const markup = 1 + ((est.profit_pct || 0) + (est.overhead_pct || 0) + (est.risk_pct || 0)) / 100;
            return sum + (est.total_cost * markup);
        }, 0);

        currentY += 30;
        doc.setFontSize(14);
        doc.setTextColor(0, 50, 150);
        doc.text(`Total Estimate: £${grandTotal.toFixed(2)}`, 14, currentY);
        doc.setTextColor(0, 0, 0);

        // VERSION MARKER (To verify update)
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text("v2.0 Generated by Constructa", 14, 280);
        doc.setTextColor(0);

        // --- PAGE 2: ABOUT US ---
        if (profile?.bio_text) {
            doc.addPage();
            currentY = 20;
            doc.setFontSize(16);
            doc.setFont("helvetica", "bold");
            doc.text(`About ${profile.company_name}`, 14, currentY);

            currentY += 10;
            doc.setFontSize(11);
            doc.setFont("helvetica", "normal");
            const bioLines = doc.splitTextToSize(profile.bio_text, 180);
            doc.text(bioLines, 14, currentY);
            currentY += (bioLines.length * 5) + 10;

            if (profile.usp_text) {
                doc.setFont("helvetica", "bold");
                doc.text("Why Choose Us?", 14, currentY);
                currentY += 7;
                doc.setFont("helvetica", "normal");
                const uspLines = doc.splitTextToSize(profile.usp_text, 180);
                doc.text(uspLines, 14, currentY);
            }
        }

        // --- PAGE 3: SCOPE & SCHEDULE ---
        doc.addPage();
        currentY = 20;

        // 1. SCOPE NARRATIVE
        if (project.scope_text) {
            doc.setFontSize(14);
            doc.setFont("helvetica", "bold");
            doc.text("Scope of Works", 14, currentY);
            currentY += 10;

            doc.setFontSize(10);
            doc.setFont("helvetica", "normal");
            const splitScope = doc.splitTextToSize(project.scope_text, 180);
            doc.text(splitScope, 14, currentY);
            currentY += (splitScope.length * 5) + 10;
        }

        // ⚠️ CRITICAL CHANGE: NO "ELSE" HERE. WE PRINT THE REST REGARDLESS.

        // 2. PROPOSED SCHEDULE
        currentY = checkPageBreak(currentY, 60);
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text("Proposed Schedule", 14, currentY);
        currentY += 10;

        estimates.forEach((est, index) => {
            currentY = checkPageBreak(currentY, 15);
            doc.setFontSize(10);
            doc.setFont("helvetica", "bold");
            doc.text(`${index + 1}. ${est.version_name}`, 14, currentY);

            doc.setFont("helvetica", "normal");
            doc.text("Duration: TBC", 140, currentY);

            doc.setDrawColor(200);
            doc.line(14, currentY + 2, 180, currentY + 2);
            currentY += 8;
        });

        currentY += 10;

        // 3. FINANCIAL BREAKDOWN
        currentY = checkPageBreak(currentY, 60);
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text("Financial Breakdown", 14, currentY);
        currentY += 10;

        estimates.forEach(est => {
            const markup = 1 + ((est.profit_pct || 0) + (est.overhead_pct || 0) + (est.risk_pct || 0)) / 100;
            const total = est.total_cost * markup;

            currentY = checkPageBreak(currentY, 20);

            doc.setFillColor(245, 247, 250);
            doc.rect(14, currentY - 6, 180, 8, 'F');

            doc.setFontSize(10);
            doc.setFont("helvetica", "bold");
            doc.text(est.version_name, 16, currentY);
            doc.text(`£${total.toFixed(2)}`, 170, currentY);
            currentY += 8;

            if (est.estimate_lines) {
                est.estimate_lines.forEach((line: any) => {
                    currentY = checkPageBreak(currentY, 10);
                    doc.setFont("helvetica", "normal");
                    doc.setFontSize(9);
                    doc.text(`- ${line.description}`, 20, currentY);
                    doc.text(`${line.quantity} ${line.unit}`, 140, currentY);
                    currentY += 5;
                });
            }
            currentY += 5;
        });

        // --- PAGE 4: TERMS ---
        doc.addPage();
        currentY = 20;
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text("Terms, Exclusions & Clarifications", 14, currentY);
        currentY += 10;

        const clarText = project.clarifications_text || project.clarifications;
        if (clarText) {
            doc.setFontSize(11);
            doc.setFont("helvetica", "bold");
            doc.text("Clarifications:", 14, currentY);
            currentY += 7;
            doc.setFont("helvetica", "normal");
            doc.setFontSize(10);
            const lines = doc.splitTextToSize(clarText, 180);
            doc.text(lines, 14, currentY);
            currentY += (lines.length * 5) + 10;
        }

        const exclText = project.exclusions_text || project.exclusions;
        if (exclText) {
            doc.setFontSize(11);
            doc.setFont("helvetica", "bold");
            doc.text("Exclusions:", 14, currentY);
            currentY += 7;
            doc.setFont("helvetica", "normal");
            doc.setFontSize(10);
            const lines = doc.splitTextToSize(exclText, 180);
            doc.text(lines, 14, currentY);
            currentY += (lines.length * 5) + 10;
        }

        currentY += 20;
        doc.setDrawColor(0);
        doc.rect(14, currentY, 180, 40);
        doc.text("Signed on behalf of Client:", 20, currentY + 10);

        doc.save(`Proposal-${project?.name}.pdf`);
    };

    return (
        <button
            onClick={generatePDF}
            className="inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 h-10 px-4 py-2 bg-blue-600 text-white hover:bg-blue-700 shadow-sm"
        >
            Download Proposal PDF
        </button>
    );
}
