-- Fix labour rates (all 260 roles with correct UK day rates) + add consumables library

-- PART 1: Labour rates with correct values
DELETE FROM labour_rates WHERE is_system_default = TRUE;
INSERT INTO labour_rates (trade, role, day_rate, region, is_system_default) VALUES
  ('Site Setup & Preliminaries', 'Site manager', 380, 'national', TRUE),
  ('Site Setup & Preliminaries', 'General operative', 200, 'national', TRUE),
  ('Site Setup & Preliminaries', 'Traffic marshal', 220, 'national', TRUE),
  ('Site Setup & Preliminaries', 'Banksman', 220, 'national', TRUE),
  ('Site Setup & Preliminaries', 'Temporary works coordinator', 300, 'national', TRUE),
  ('Site Setup & Preliminaries', 'Gateman', 180, 'national', TRUE),
  ('Demolition & Strip Out', 'Demolition operative', 260, 'national', TRUE),
  ('Demolition & Strip Out', 'Strip-out operative', 240, 'national', TRUE),
  ('Demolition & Strip Out', 'Burner', 260, 'national', TRUE),
  ('Demolition & Strip Out', 'Plant operator', 290, 'national', TRUE),
  ('Demolition & Strip Out', 'Labourer', 200, 'national', TRUE),
  ('Demolition & Strip Out', 'Demolition supervisor', 320, 'national', TRUE),
  ('Asbestos Removal', 'Licensed asbestos operative', 380, 'national', TRUE),
  ('Asbestos Removal', 'Asbestos supervisor', 420, 'national', TRUE),
  ('Asbestos Removal', 'Analyst / air tester', 380, 'national', TRUE),
  ('Asbestos Removal', 'Labourer', 200, 'national', TRUE),
  ('Temporary Works / Propping / Shoring', 'Temporary works engineer', 400, 'national', TRUE),
  ('Temporary Works / Propping / Shoring', 'Steel erector', 340, 'national', TRUE),
  ('Temporary Works / Propping / Shoring', 'Carpenter', 280, 'national', TRUE),
  ('Temporary Works / Propping / Shoring', 'Labourer', 200, 'national', TRUE),
  ('Temporary Works / Propping / Shoring', 'Supervisor', 320, 'national', TRUE),
  ('Groundworks & Civils', 'Groundworker', 260, 'national', TRUE),
  ('Groundworks & Civils', 'Plant operator', 290, 'national', TRUE),
  ('Groundworks & Civils', 'General operative', 200, 'national', TRUE),
  ('Groundworks & Civils', 'Groundworks foreman', 340, 'national', TRUE),
  ('Groundworks & Civils', 'Setting out engineer', 360, 'national', TRUE),
  ('Drainage', 'Drainage operative', 260, 'national', TRUE),
  ('Drainage', 'Pipe layer', 260, 'national', TRUE),
  ('Drainage', 'Groundworker', 260, 'national', TRUE),
  ('Drainage', 'Plant operator', 290, 'national', TRUE),
  ('Drainage', 'Confined space operative', 290, 'national', TRUE),
  ('Utilities – Water', 'Utilities gang operative', 240, 'national', TRUE),
  ('Utilities – Water', 'Pipe layer', 260, 'national', TRUE),
  ('Utilities – Water', 'Fusion welder', 360, 'national', TRUE),
  ('Utilities – Water', 'Plant operator', 290, 'national', TRUE),
  ('Utilities – Water', 'Supervisor', 320, 'national', TRUE),
  ('Utilities – Gas', 'Gas main operative', 240, 'national', TRUE),
  ('Utilities – Gas', 'Gas engineer', 240, 'national', TRUE),
  ('Utilities – Gas', 'Pipe layer', 260, 'national', TRUE),
  ('Utilities – Gas', 'Plant operator', 290, 'national', TRUE),
  ('Utilities – Gas', 'Supervisor', 320, 'national', TRUE),
  ('Utilities – Electric / Ducting', 'Utilities operative', 270, 'national', TRUE),
  ('Utilities – Electric / Ducting', 'Cable jointer', 360, 'national', TRUE),
  ('Utilities – Electric / Ducting', 'HV/LV fitter', 240, 'national', TRUE),
  ('Utilities – Electric / Ducting', 'Plant operator', 290, 'national', TRUE),
  ('Utilities – Electric / Ducting', 'Supervisor', 320, 'national', TRUE),
  ('Utilities – Telecoms / Data Ducting', 'Utilities operative', 270, 'national', TRUE),
  ('Utilities – Telecoms / Data Ducting', 'Fibre operative', 240, 'national', TRUE),
  ('Utilities – Telecoms / Data Ducting', 'Plant operator', 290, 'national', TRUE),
  ('Utilities – Telecoms / Data Ducting', 'Supervisor', 320, 'national', TRUE),
  ('Attenuation / SuDS / Stormwater', 'Groundworker', 260, 'national', TRUE),
  ('Attenuation / SuDS / Stormwater', 'Drainage operative', 260, 'national', TRUE),
  ('Attenuation / SuDS / Stormwater', 'Plant operator', 290, 'national', TRUE),
  ('Attenuation / SuDS / Stormwater', 'Civils foreman', 340, 'national', TRUE),
  ('Piling', 'Piling operative', 300, 'national', TRUE),
  ('Piling', 'Piling rig operator', 380, 'national', TRUE),
  ('Piling', 'Steel fixer', 300, 'national', TRUE),
  ('Piling', 'Concrete operative', 260, 'national', TRUE),
  ('Piling', 'Supervisor', 320, 'national', TRUE),
  ('Underpinning & Structural Stabilisation', 'Groundworker', 260, 'national', TRUE),
  ('Underpinning & Structural Stabilisation', 'Concrete operative', 260, 'national', TRUE),
  ('Underpinning & Structural Stabilisation', 'Steel fixer', 300, 'national', TRUE),
  ('Underpinning & Structural Stabilisation', 'Bricklayer', 280, 'national', TRUE),
  ('Underpinning & Structural Stabilisation', 'Supervisor', 320, 'national', TRUE),
  ('Concrete / RC Works', 'Concrete finisher', 280, 'national', TRUE),
  ('Concrete / RC Works', 'Shuttering carpenter', 290, 'national', TRUE),
  ('Concrete / RC Works', 'Steel fixer', 300, 'national', TRUE),
  ('Concrete / RC Works', 'Concrete operative', 260, 'national', TRUE),
  ('Concrete / RC Works', 'Supervisor', 320, 'national', TRUE),
  ('Steel Frame / Steel Erection', 'Steel erector', 340, 'national', TRUE),
  ('Steel Frame / Steel Erection', 'Welder', 340, 'national', TRUE),
  ('Steel Frame / Steel Erection', 'Fabricator', 320, 'national', TRUE),
  ('Steel Frame / Steel Erection', 'Slinger signaller', 240, 'national', TRUE),
  ('Steel Frame / Steel Erection', 'Banksman', 220, 'national', TRUE),
  ('Steel Frame / Steel Erection', 'Supervisor', 320, 'national', TRUE),
  ('Structural Timber / Framing', 'Timber framer', 290, 'national', TRUE),
  ('Structural Timber / Framing', 'Carpenter', 280, 'national', TRUE),
  ('Structural Timber / Framing', 'Joiner', 280, 'national', TRUE),
  ('Structural Timber / Framing', 'Labourer', 200, 'national', TRUE),
  ('Structural Timber / Framing', 'Supervisor', 320, 'national', TRUE),
  ('Masonry / Brickwork / Blockwork', 'Bricklayer', 280, 'national', TRUE),
  ('Masonry / Brickwork / Blockwork', 'Block layer', 270, 'national', TRUE),
  ('Masonry / Brickwork / Blockwork', 'Mason', 300, 'national', TRUE),
  ('Masonry / Brickwork / Blockwork', 'Labourer', 200, 'national', TRUE),
  ('Masonry / Brickwork / Blockwork', 'Foreman', 340, 'national', TRUE),
  ('Cladding & Rainscreen', 'Cladder', 290, 'national', TRUE),
  ('Cladding & Rainscreen', 'Façade installer', 240, 'national', TRUE),
  ('Cladding & Rainscreen', 'Carpenter', 280, 'national', TRUE),
  ('Cladding & Rainscreen', 'Steel fixer', 300, 'national', TRUE),
  ('Cladding & Rainscreen', 'Labourer', 200, 'national', TRUE),
  ('Cladding & Rainscreen', 'Supervisor', 320, 'national', TRUE),
  ('Roofing', 'Roofer', 280, 'national', TRUE),
  ('Roofing', 'Slater', 290, 'national', TRUE),
  ('Roofing', 'Tiler', 270, 'national', TRUE),
  ('Roofing', 'Leadworker', 320, 'national', TRUE),
  ('Roofing', 'Flat roofer', 280, 'national', TRUE),
  ('Waterproofing', 'Waterproofing operative', 270, 'national', TRUE),
  ('Waterproofing', 'Flat roofer', 280, 'national', TRUE),
  ('Waterproofing', 'Concrete operative', 260, 'national', TRUE),
  ('Waterproofing', 'Supervisor', 320, 'national', TRUE),
  ('Insulation', 'Insulation installer', 250, 'national', TRUE),
  ('Insulation', 'Dryliner', 260, 'national', TRUE),
  ('Insulation', 'Roofer', 280, 'national', TRUE),
  ('Insulation', 'External wall operative', 240, 'national', TRUE),
  ('Windows, Doors & Glazing', 'Window fitter', 270, 'national', TRUE),
  ('Windows, Doors & Glazing', 'Glazier', 290, 'national', TRUE),
  ('Windows, Doors & Glazing', 'Door installer', 240, 'national', TRUE),
  ('Windows, Doors & Glazing', 'Labourer', 200, 'national', TRUE),
  ('Builders / General Building', 'General builder', 260, 'national', TRUE),
  ('Builders / General Building', 'Multi-trader', 270, 'national', TRUE),
  ('Builders / General Building', 'Carpenter', 280, 'national', TRUE),
  ('Builders / General Building', 'Bricklayer', 280, 'national', TRUE),
  ('Builders / General Building', 'Labourer', 200, 'national', TRUE),
  ('Builders / General Building', 'Supervisor', 320, 'national', TRUE),
  ('Loft Conversion / Extension / Domestic Framing', 'Carpenter', 280, 'national', TRUE),
  ('Loft Conversion / Extension / Domestic Framing', 'Timber framer', 290, 'national', TRUE),
  ('Loft Conversion / Extension / Domestic Framing', 'Roofer', 280, 'national', TRUE),
  ('Loft Conversion / Extension / Domestic Framing', 'General builder', 260, 'national', TRUE),
  ('Loft Conversion / Extension / Domestic Framing', 'Bricklayer', 280, 'national', TRUE),
  ('Conservatories / Garden Rooms / Outbuildings', 'Installer', 240, 'national', TRUE),
  ('Conservatories / Garden Rooms / Outbuildings', 'Carpenter', 280, 'national', TRUE),
  ('Conservatories / Garden Rooms / Outbuildings', 'Groundworker', 260, 'national', TRUE),
  ('Conservatories / Garden Rooms / Outbuildings', 'Roofer', 280, 'national', TRUE),
  ('Conservatories / Garden Rooms / Outbuildings', 'Electrician', 320, 'national', TRUE),
  ('Landscaping & External Works', 'Landscaper', 240, 'national', TRUE),
  ('Landscaping & External Works', 'Soft landscaper', 230, 'national', TRUE),
  ('Landscaping & External Works', 'Fencer', 240, 'national', TRUE),
  ('Landscaping & External Works', 'Irrigation operative', 240, 'national', TRUE),
  ('Surfacing, Paving & Kerbing', 'Paver', 260, 'national', TRUE),
  ('Surfacing, Paving & Kerbing', 'Groundworker', 260, 'national', TRUE),
  ('Surfacing, Paving & Kerbing', 'Roller driver', 240, 'national', TRUE),
  ('Surfacing, Paving & Kerbing', 'Surfacing operative', 260, 'national', TRUE),
  ('Line Marking & Road Furniture', 'Line marking operative', 240, 'national', TRUE),
  ('Line Marking & Road Furniture', 'General operative', 200, 'national', TRUE),
  ('Line Marking & Road Furniture', 'Supervisor', 320, 'national', TRUE),
  ('External Lighting', 'Electrician', 320, 'national', TRUE),
  ('External Lighting', 'Civils operative', 260, 'national', TRUE),
  ('External Lighting', 'Plant operator', 290, 'national', TRUE),
  ('External Lighting', 'Supervisor', 320, 'national', TRUE),
  ('Signage', 'Sign installer', 260, 'national', TRUE),
  ('Signage', 'Fabricator', 320, 'national', TRUE),
  ('Signage', 'Electrician', 320, 'national', TRUE),
  ('Signage', 'General operative', 200, 'national', TRUE),
  ('Fencing & Gates', 'Fencer', 240, 'national', TRUE),
  ('Fencing & Gates', 'Groundworker', 260, 'national', TRUE),
  ('Fencing & Gates', 'Welder', 340, 'national', TRUE),
  ('Fencing & Gates', 'Labourer', 200, 'national', TRUE),
  ('Swimming Pools & Water Features', 'Pool installer', 290, 'national', TRUE),
  ('Swimming Pools & Water Features', 'Groundworker', 260, 'national', TRUE),
  ('Swimming Pools & Water Features', 'Steel fixer', 300, 'national', TRUE),
  ('Swimming Pools & Water Features', 'Concrete operative', 260, 'national', TRUE),
  ('Swimming Pools & Water Features', 'Tiler', 270, 'national', TRUE),
  ('Swimming Pools & Water Features', 'Waterproofing operative', 270, 'national', TRUE),
  ('Swimming Pools & Water Features', 'Plumber', 300, 'national', TRUE),
  ('Swimming Pools & Water Features', 'Electrician', 320, 'national', TRUE),
  ('Domestic Electrical', 'Electrician', 320, 'national', TRUE),
  ('Domestic Electrical', 'Approved electrician', 340, 'national', TRUE),
  ('Domestic Electrical', 'Electrical mate', 210, 'national', TRUE),
  ('Domestic Electrical', 'Test engineer', 320, 'national', TRUE),
  ('Commercial Electrical', 'Electrician', 320, 'national', TRUE),
  ('Commercial Electrical', 'Approved electrician', 340, 'national', TRUE),
  ('Commercial Electrical', 'Electrical improver', 240, 'national', TRUE),
  ('Commercial Electrical', 'Mate', 210, 'national', TRUE),
  ('Commercial Electrical', 'Supervisor', 320, 'national', TRUE),
  ('Industrial Electrical', 'Industrial electrician', 360, 'national', TRUE),
  ('Industrial Electrical', 'Cable jointer', 360, 'national', TRUE),
  ('Industrial Electrical', 'Instrument technician', 240, 'national', TRUE),
  ('Industrial Electrical', 'Panel wireman', 240, 'national', TRUE),
  ('Industrial Electrical', 'Supervisor', 320, 'national', TRUE),
  ('EV Chargers', 'EV charge point installer', 320, 'national', TRUE),
  ('EV Chargers', 'Electrician', 320, 'national', TRUE),
  ('EV Chargers', 'Groundworker', 260, 'national', TRUE),
  ('EV Chargers', 'Civils operative', 260, 'national', TRUE),
  ('Street Electrical / Feeder Pillars', 'Electrician', 320, 'national', TRUE),
  ('Street Electrical / Feeder Pillars', 'Utilities operative', 270, 'national', TRUE),
  ('Street Electrical / Feeder Pillars', 'Civils operative', 260, 'national', TRUE),
  ('Street Electrical / Feeder Pillars', 'Supervisor', 320, 'national', TRUE),
  ('Substations', 'HV electrician', 420, 'national', TRUE),
  ('Substations', 'Cable jointer', 360, 'national', TRUE),
  ('Substations', 'Fitter', 240, 'national', TRUE),
  ('Substations', 'Civils operative', 260, 'national', TRUE),
  ('Substations', 'Supervisor', 320, 'national', TRUE),
  ('Domestic Plumbing', 'Plumber', 300, 'national', TRUE),
  ('Domestic Plumbing', 'Plumber’s mate', 300, 'national', TRUE),
  ('Domestic Plumbing', 'Heating engineer', 310, 'national', TRUE),
  ('Commercial Plumbing / Public Health', 'Plumber', 300, 'national', TRUE),
  ('Commercial Plumbing / Public Health', 'Pipefitter', 310, 'national', TRUE),
  ('Commercial Plumbing / Public Health', 'Public health engineer', 340, 'national', TRUE),
  ('Commercial Plumbing / Public Health', 'Mate', 210, 'national', TRUE),
  ('Commercial Plumbing / Public Health', 'Supervisor', 320, 'national', TRUE),
  ('Mechanical / HVAC', 'Mechanical fitter', 310, 'national', TRUE),
  ('Mechanical / HVAC', 'HVAC installer', 310, 'national', TRUE),
  ('Mechanical / HVAC', 'Duct fitter', 290, 'national', TRUE),
  ('Mechanical / HVAC', 'Pipefitter', 310, 'national', TRUE),
  ('Mechanical / HVAC', 'Mate', 210, 'national', TRUE),
  ('Mechanical / HVAC', 'Supervisor', 320, 'national', TRUE),
  ('Domestic Heating', 'Heating engineer', 310, 'national', TRUE),
  ('Domestic Heating', 'Gas Safe engineer', 320, 'national', TRUE),
  ('Domestic Heating', 'Plumber', 300, 'national', TRUE),
  ('Air Conditioning / Refrigeration', 'AC installer', 310, 'national', TRUE),
  ('Air Conditioning / Refrigeration', 'Refrigeration engineer', 330, 'national', TRUE),
  ('Air Conditioning / Refrigeration', 'Electrician', 320, 'national', TRUE),
  ('Air Conditioning / Refrigeration', 'Mate', 210, 'national', TRUE),
  ('Fire Alarm & Life Safety', 'Fire alarm engineer', 300, 'national', TRUE),
  ('Fire Alarm & Life Safety', 'Electrician', 320, 'national', TRUE),
  ('Fire Alarm & Life Safety', 'Commissioning engineer', 360, 'national', TRUE),
  ('Security / CCTV / Access Control', 'Security engineer', 290, 'national', TRUE),
  ('Security / CCTV / Access Control', 'Electrician', 320, 'national', TRUE),
  ('Security / CCTV / Access Control', 'Data installer', 270, 'national', TRUE),
  ('Drylining & Partitions', 'Dryliner', 260, 'national', TRUE),
  ('Drylining & Partitions', 'Ceiling fixer', 260, 'national', TRUE),
  ('Drylining & Partitions', 'Partition fixer', 240, 'national', TRUE),
  ('Drylining & Partitions', 'Labourer', 200, 'national', TRUE),
  ('Plastering & Rendering', 'Plasterer', 280, 'national', TRUE),
  ('Plastering & Rendering', 'Renderer', 270, 'national', TRUE),
  ('Plastering & Rendering', 'Labourer', 200, 'national', TRUE),
  ('Carpentry & Joinery', 'Carpenter', 280, 'national', TRUE),
  ('Carpentry & Joinery', 'Joiner', 280, 'national', TRUE),
  ('Carpentry & Joinery', 'Bench joiner', 290, 'national', TRUE),
  ('Kitchen Installation', 'Kitchen fitter', 280, 'national', TRUE),
  ('Kitchen Installation', 'Carpenter', 280, 'national', TRUE),
  ('Kitchen Installation', 'Plumber', 300, 'national', TRUE),
  ('Kitchen Installation', 'Electrician', 320, 'national', TRUE),
  ('Bathroom Installation', 'Bathroom fitter', 270, 'national', TRUE),
  ('Bathroom Installation', 'Plumber', 300, 'national', TRUE),
  ('Bathroom Installation', 'Tiler', 270, 'national', TRUE),
  ('Bathroom Installation', 'Electrician', 320, 'national', TRUE),
  ('Tiling', 'Tiler', 270, 'national', TRUE),
  ('Tiling', 'Labourer', 200, 'national', TRUE),
  ('Flooring', 'Floor layer', 260, 'national', TRUE),
  ('Flooring', 'Carpet fitter', 250, 'national', TRUE),
  ('Flooring', 'Vinyl installer', 240, 'national', TRUE),
  ('Flooring', 'Wood floor installer', 240, 'national', TRUE),
  ('Ceilings', 'Ceiling fixer', 260, 'national', TRUE),
  ('Ceilings', 'Dryliner', 260, 'national', TRUE),
  ('Ceilings', 'Labourer', 200, 'national', TRUE),
  ('Painting & Decorating', 'Painter and decorator', 260, 'national', TRUE),
  ('Painting & Decorating', 'Spray painter', 250, 'national', TRUE),
  ('Painting & Decorating', 'Paperhanger', 240, 'national', TRUE),
  ('Fire Stopping', 'Fire stopping operative', 270, 'national', TRUE),
  ('Fire Stopping', 'Dryliner', 260, 'national', TRUE),
  ('Fire Stopping', 'Supervisor', 320, 'national', TRUE),
  ('Passive Fire Protection / Intumescent', 'Intumescent applicator', 270, 'national', TRUE),
  ('Passive Fire Protection / Intumescent', 'Painter', 250, 'national', TRUE),
  ('Passive Fire Protection / Intumescent', 'Supervisor', 320, 'national', TRUE),
  ('Diamond Drilling & Sawing', 'Diamond driller', 320, 'national', TRUE),
  ('Diamond Drilling & Sawing', 'Saw operative', 280, 'national', TRUE),
  ('Diamond Drilling & Sawing', 'Labourer', 200, 'national', TRUE),
  ('Builderswork in Connection', 'General builder', 260, 'national', TRUE),
  ('Builderswork in Connection', 'Labourer', 200, 'national', TRUE),
  ('Builderswork in Connection', 'Carpenter', 280, 'national', TRUE),
  ('Builderswork in Connection', 'Groundworker', 260, 'national', TRUE),
  ('Specialist Finishes', 'Specialist finisher', 300, 'national', TRUE),
  ('Specialist Finishes', 'Resin flooring operative', 280, 'national', TRUE),
  ('Specialist Finishes', 'Plaster artisan', 240, 'national', TRUE),
  ('Waste Management / Logistics', 'Site labourer', 200, 'national', TRUE),
  ('Waste Management / Logistics', 'Traffic marshal', 220, 'national', TRUE),
  ('Waste Management / Logistics', 'Gateman', 180, 'national', TRUE),
  ('Waste Management / Logistics', 'Storeman', 240, 'national', TRUE),
  ('Waste Management / Logistics', 'Supervisor', 320, 'national', TRUE) ON CONFLICT DO NOTHING;

-- PART 2: Consumables library
DELETE FROM cost_library_items WHERE category = 'Consumables' AND is_system_default = TRUE;
INSERT INTO cost_library_items (code, description, unit, base_rate, category, is_system_default) VALUES
  ('CONS-001', 'Diesel fuel', 'litre', 1.45, 'Consumables', TRUE),
  ('CONS-002', 'Petrol', 'litre', 1.5, 'Consumables', TRUE),
  ('CONS-003', 'LPG gas bottle', 'nr', 28.0, 'Consumables', TRUE),
  ('CONS-004', 'Hard hat', 'nr', 8.5, 'Consumables', TRUE),
  ('CONS-005', 'Hi-vis vest', 'nr', 4.0, 'Consumables', TRUE),
  ('CONS-006', 'Safety boots (pair)', 'nr', 45.0, 'Consumables', TRUE),
  ('CONS-007', 'Gloves (box)', 'box', 12.0, 'Consumables', TRUE),
  ('CONS-008', 'Safety glasses', 'nr', 3.5, 'Consumables', TRUE),
  ('CONS-009', 'Dust mask FFP3', 'nr', 2.5, 'Consumables', TRUE),
  ('CONS-010', 'Ear defenders', 'nr', 8.0, 'Consumables', TRUE),
  ('CONS-011', 'Disposable overalls', 'nr', 6.0, 'Consumables', TRUE),
  ('CONS-012', 'Screws (box 200no)', 'box', 8.5, 'Consumables', TRUE),
  ('CONS-013', 'Nails (2kg box)', 'box', 6.0, 'Consumables', TRUE),
  ('CONS-014', 'Bolts and nuts (bag)', 'bag', 12.0, 'Consumables', TRUE),
  ('CONS-015', 'Resin anchors (box)', 'box', 35.0, 'Consumables', TRUE),
  ('CONS-016', 'Wall plugs (bag)', 'bag', 4.0, 'Consumables', TRUE),
  ('CONS-017', 'Self-tapping screws (box)', 'box', 7.5, 'Consumables', TRUE),
  ('CONS-018', 'Silicone sealant', 'nr', 4.5, 'Consumables', TRUE),
  ('CONS-019', 'Frame sealant', 'nr', 4.0, 'Consumables', TRUE),
  ('CONS-020', 'PVA adhesive (5L)', 'nr', 12.0, 'Consumables', TRUE),
  ('CONS-021', 'Expanding foam', 'nr', 8.5, 'Consumables', TRUE),
  ('CONS-022', 'Duct tape (roll)', 'nr', 6.0, 'Consumables', TRUE),
  ('CONS-023', 'Masking tape (roll)', 'nr', 2.5, 'Consumables', TRUE),
  ('CONS-024', 'Polythene sheeting (25m roll)', 'roll', 18.0, 'Consumables', TRUE),
  ('CONS-025', 'DPM membrane (25m roll)', 'roll', 45.0, 'Consumables', TRUE),
  ('CONS-026', 'Protection board (sheet)', 'nr', 12.0, 'Consumables', TRUE),
  ('CONS-027', 'Dust sheets (pair)', 'pair', 15.0, 'Consumables', TRUE),
  ('CONS-028', 'Cable ties (bag)', 'bag', 4.5, 'Consumables', TRUE),
  ('CONS-029', 'Warning tape (roll)', 'roll', 3.5, 'Consumables', TRUE),
  ('CONS-030', 'Skip liner bag', 'nr', 8.0, 'Consumables', TRUE),
  ('CONS-031', 'Debris bag (heavy duty)', 'nr', 2.5, 'Consumables', TRUE),
  ('CONS-032', 'Release agent (5L)', 'nr', 18.0, 'Consumables', TRUE),
  ('CONS-033', 'Curing compound (5L)', 'nr', 22.0, 'Consumables', TRUE),
  ('CONS-034', 'Concrete cover spacers (bag)', 'bag', 8.0, 'Consumables', TRUE),
  ('CONS-035', 'Tie wire (coil)', 'coil', 12.0, 'Consumables', TRUE),
  ('CONS-036', 'Cable clips (bag)', 'bag', 3.5, 'Consumables', TRUE),
  ('CONS-037', 'PTFE tape (roll)', 'roll', 1.5, 'Consumables', TRUE),
  ('CONS-038', 'Flux paste (tin)', 'nr', 6.0, 'Consumables', TRUE),
  ('CONS-039', 'Solder (roll)', 'roll', 12.0, 'Consumables', TRUE),
  ('CONS-040', 'Wire connectors (bag)', 'bag', 4.0, 'Consumables', TRUE),
  ('CONS-041', 'Marker pens (pack)', 'pack', 6.0, 'Consumables', TRUE),
  ('CONS-042', 'Chalk line', 'nr', 8.0, 'Consumables', TRUE),
  ('CONS-043', 'Pencils (pack)', 'pack', 2.5, 'Consumables', TRUE),
  ('CONS-044', 'Wheelbarrow', 'nr', 65.0, 'Consumables', TRUE),
  ('CONS-045', 'Buckets (each)', 'nr', 4.5, 'Consumables', TRUE),
  ('CONS-046', 'Mixing tub (each)', 'nr', 12.0, 'Consumables', TRUE) ON CONFLICT DO NOTHING;