-- Sprint 9c: Full 60-trade master library import (1038 items)
-- Replaces previous partial import

-- LABOUR RATES (260 roles)
DELETE FROM labour_rates WHERE is_system_default = TRUE;
INSERT INTO labour_rates (trade, role, day_rate, region, is_system_default) VALUES
  ('Site Setup & Preliminaries', 'Site manager', 0, 'national', TRUE),
  ('Site Setup & Preliminaries', 'General operative', 0, 'national', TRUE),
  ('Site Setup & Preliminaries', 'Traffic marshal', 0, 'national', TRUE),
  ('Site Setup & Preliminaries', 'Banksman', 0, 'national', TRUE),
  ('Site Setup & Preliminaries', 'Temporary works coordinator', 0, 'national', TRUE),
  ('Site Setup & Preliminaries', 'Gateman', 0, 'national', TRUE),
  ('Demolition & Strip Out', 'Demolition operative', 0, 'national', TRUE),
  ('Demolition & Strip Out', 'Strip-out operative', 0, 'national', TRUE),
  ('Demolition & Strip Out', 'Burner', 0, 'national', TRUE),
  ('Demolition & Strip Out', 'Plant operator', 0, 'national', TRUE),
  ('Demolition & Strip Out', 'Labourer', 0, 'national', TRUE),
  ('Demolition & Strip Out', 'Demolition supervisor', 0, 'national', TRUE),
  ('Asbestos Removal', 'Licensed asbestos operative', 0, 'national', TRUE),
  ('Asbestos Removal', 'Asbestos supervisor', 0, 'national', TRUE),
  ('Asbestos Removal', 'Analyst / air tester', 0, 'national', TRUE),
  ('Asbestos Removal', 'Labourer', 0, 'national', TRUE),
  ('Temporary Works / Propping / Shoring', 'Temporary works engineer', 0, 'national', TRUE),
  ('Temporary Works / Propping / Shoring', 'Steel erector', 0, 'national', TRUE),
  ('Temporary Works / Propping / Shoring', 'Carpenter', 0, 'national', TRUE),
  ('Temporary Works / Propping / Shoring', 'Labourer', 0, 'national', TRUE),
  ('Temporary Works / Propping / Shoring', 'Supervisor', 0, 'national', TRUE),
  ('Groundworks & Civils', 'Groundworker', 0, 'national', TRUE),
  ('Groundworks & Civils', 'Plant operator', 0, 'national', TRUE),
  ('Groundworks & Civils', 'General operative', 0, 'national', TRUE),
  ('Groundworks & Civils', 'Groundworks foreman', 0, 'national', TRUE),
  ('Groundworks & Civils', 'Setting out engineer', 0, 'national', TRUE),
  ('Drainage', 'Drainage operative', 0, 'national', TRUE),
  ('Drainage', 'Pipe layer', 0, 'national', TRUE),
  ('Drainage', 'Groundworker', 0, 'national', TRUE),
  ('Drainage', 'Plant operator', 0, 'national', TRUE),
  ('Drainage', 'Confined space operative', 0, 'national', TRUE),
  ('Utilities – Water', 'Utilities gang operative', 0, 'national', TRUE),
  ('Utilities – Water', 'Pipe layer', 0, 'national', TRUE),
  ('Utilities – Water', 'Fusion welder', 0, 'national', TRUE),
  ('Utilities – Water', 'Plant operator', 0, 'national', TRUE),
  ('Utilities – Water', 'Supervisor', 0, 'national', TRUE),
  ('Utilities – Gas', 'Gas main operative', 0, 'national', TRUE),
  ('Utilities – Gas', 'Gas engineer', 0, 'national', TRUE),
  ('Utilities – Gas', 'Pipe layer', 0, 'national', TRUE),
  ('Utilities – Gas', 'Plant operator', 0, 'national', TRUE),
  ('Utilities – Gas', 'Supervisor', 0, 'national', TRUE),
  ('Utilities – Electric / Ducting', 'Utilities operative', 0, 'national', TRUE),
  ('Utilities – Electric / Ducting', 'Cable jointer', 0, 'national', TRUE),
  ('Utilities – Electric / Ducting', 'HV/LV fitter', 0, 'national', TRUE),
  ('Utilities – Electric / Ducting', 'Plant operator', 0, 'national', TRUE),
  ('Utilities – Electric / Ducting', 'Supervisor', 0, 'national', TRUE),
  ('Utilities – Telecoms / Data Ducting', 'Utilities operative', 0, 'national', TRUE),
  ('Utilities – Telecoms / Data Ducting', 'Fibre operative', 0, 'national', TRUE),
  ('Utilities – Telecoms / Data Ducting', 'Plant operator', 0, 'national', TRUE),
  ('Utilities – Telecoms / Data Ducting', 'Supervisor', 0, 'national', TRUE),
  ('Attenuation / SuDS / Stormwater', 'Groundworker', 0, 'national', TRUE),
  ('Attenuation / SuDS / Stormwater', 'Drainage operative', 0, 'national', TRUE),
  ('Attenuation / SuDS / Stormwater', 'Plant operator', 0, 'national', TRUE),
  ('Attenuation / SuDS / Stormwater', 'Civils foreman', 0, 'national', TRUE),
  ('Piling', 'Piling operative', 0, 'national', TRUE),
  ('Piling', 'Piling rig operator', 0, 'national', TRUE),
  ('Piling', 'Steel fixer', 0, 'national', TRUE),
  ('Piling', 'Concrete operative', 0, 'national', TRUE),
  ('Piling', 'Supervisor', 0, 'national', TRUE),
  ('Underpinning & Structural Stabilisation', 'Groundworker', 0, 'national', TRUE),
  ('Underpinning & Structural Stabilisation', 'Concrete operative', 0, 'national', TRUE),
  ('Underpinning & Structural Stabilisation', 'Steel fixer', 0, 'national', TRUE),
  ('Underpinning & Structural Stabilisation', 'Bricklayer', 0, 'national', TRUE),
  ('Underpinning & Structural Stabilisation', 'Supervisor', 0, 'national', TRUE),
  ('Concrete / RC Works', 'Concrete finisher', 0, 'national', TRUE),
  ('Concrete / RC Works', 'Shuttering carpenter', 0, 'national', TRUE),
  ('Concrete / RC Works', 'Steel fixer', 0, 'national', TRUE),
  ('Concrete / RC Works', 'Concrete operative', 0, 'national', TRUE),
  ('Concrete / RC Works', 'Supervisor', 0, 'national', TRUE),
  ('Steel Frame / Steel Erection', 'Steel erector', 0, 'national', TRUE),
  ('Steel Frame / Steel Erection', 'Welder', 0, 'national', TRUE),
  ('Steel Frame / Steel Erection', 'Fabricator', 0, 'national', TRUE),
  ('Steel Frame / Steel Erection', 'Slinger signaller', 0, 'national', TRUE),
  ('Steel Frame / Steel Erection', 'Banksman', 0, 'national', TRUE),
  ('Steel Frame / Steel Erection', 'Supervisor', 0, 'national', TRUE),
  ('Structural Timber / Framing', 'Timber framer', 0, 'national', TRUE),
  ('Structural Timber / Framing', 'Carpenter', 0, 'national', TRUE),
  ('Structural Timber / Framing', 'Joiner', 0, 'national', TRUE),
  ('Structural Timber / Framing', 'Labourer', 0, 'national', TRUE),
  ('Structural Timber / Framing', 'Supervisor', 0, 'national', TRUE),
  ('Masonry / Brickwork / Blockwork', 'Bricklayer', 0, 'national', TRUE),
  ('Masonry / Brickwork / Blockwork', 'Block layer', 0, 'national', TRUE),
  ('Masonry / Brickwork / Blockwork', 'Mason', 0, 'national', TRUE),
  ('Masonry / Brickwork / Blockwork', 'Labourer', 0, 'national', TRUE),
  ('Masonry / Brickwork / Blockwork', 'Foreman', 0, 'national', TRUE),
  ('Cladding & Rainscreen', 'Cladder', 0, 'national', TRUE),
  ('Cladding & Rainscreen', 'Façade installer', 0, 'national', TRUE),
  ('Cladding & Rainscreen', 'Carpenter', 0, 'national', TRUE),
  ('Cladding & Rainscreen', 'Steel fixer', 0, 'national', TRUE),
  ('Cladding & Rainscreen', 'Labourer', 0, 'national', TRUE),
  ('Cladding & Rainscreen', 'Supervisor', 0, 'national', TRUE),
  ('Roofing', 'Roofer', 0, 'national', TRUE),
  ('Roofing', 'Slater', 0, 'national', TRUE),
  ('Roofing', 'Tiler', 0, 'national', TRUE),
  ('Roofing', 'Leadworker', 0, 'national', TRUE),
  ('Roofing', 'Flat roofer', 0, 'national', TRUE),
  ('Waterproofing', 'Waterproofing operative', 0, 'national', TRUE),
  ('Waterproofing', 'Flat roofer', 0, 'national', TRUE),
  ('Waterproofing', 'Concrete operative', 0, 'national', TRUE),
  ('Waterproofing', 'Supervisor', 0, 'national', TRUE),
  ('Insulation', 'Insulation installer', 0, 'national', TRUE),
  ('Insulation', 'Dryliner', 0, 'national', TRUE),
  ('Insulation', 'Roofer', 0, 'national', TRUE),
  ('Insulation', 'External wall operative', 0, 'national', TRUE),
  ('Windows, Doors & Glazing', 'Window fitter', 0, 'national', TRUE),
  ('Windows, Doors & Glazing', 'Glazier', 0, 'national', TRUE),
  ('Windows, Doors & Glazing', 'Door installer', 0, 'national', TRUE),
  ('Windows, Doors & Glazing', 'Labourer', 0, 'national', TRUE),
  ('Builders / General Building', 'General builder', 0, 'national', TRUE),
  ('Builders / General Building', 'Multi-trader', 0, 'national', TRUE),
  ('Builders / General Building', 'Carpenter', 0, 'national', TRUE),
  ('Builders / General Building', 'Bricklayer', 0, 'national', TRUE),
  ('Builders / General Building', 'Labourer', 0, 'national', TRUE),
  ('Builders / General Building', 'Supervisor', 0, 'national', TRUE),
  ('Loft Conversion / Extension / Domestic Framing', 'Carpenter', 0, 'national', TRUE),
  ('Loft Conversion / Extension / Domestic Framing', 'Timber framer', 0, 'national', TRUE),
  ('Loft Conversion / Extension / Domestic Framing', 'Roofer', 0, 'national', TRUE),
  ('Loft Conversion / Extension / Domestic Framing', 'General builder', 0, 'national', TRUE),
  ('Loft Conversion / Extension / Domestic Framing', 'Bricklayer', 0, 'national', TRUE),
  ('Conservatories / Garden Rooms / Outbuildings', 'Installer', 0, 'national', TRUE),
  ('Conservatories / Garden Rooms / Outbuildings', 'Carpenter', 0, 'national', TRUE),
  ('Conservatories / Garden Rooms / Outbuildings', 'Groundworker', 0, 'national', TRUE),
  ('Conservatories / Garden Rooms / Outbuildings', 'Roofer', 0, 'national', TRUE),
  ('Conservatories / Garden Rooms / Outbuildings', 'Electrician', 0, 'national', TRUE),
  ('Landscaping & External Works', 'Landscaper', 0, 'national', TRUE),
  ('Landscaping & External Works', 'Soft landscaper', 0, 'national', TRUE),
  ('Landscaping & External Works', 'Fencer', 0, 'national', TRUE),
  ('Landscaping & External Works', 'Irrigation operative', 0, 'national', TRUE),
  ('Surfacing, Paving & Kerbing', 'Paver', 0, 'national', TRUE),
  ('Surfacing, Paving & Kerbing', 'Groundworker', 0, 'national', TRUE),
  ('Surfacing, Paving & Kerbing', 'Roller driver', 0, 'national', TRUE),
  ('Surfacing, Paving & Kerbing', 'Surfacing operative', 0, 'national', TRUE),
  ('Line Marking & Road Furniture', 'Line marking operative', 0, 'national', TRUE),
  ('Line Marking & Road Furniture', 'General operative', 0, 'national', TRUE),
  ('Line Marking & Road Furniture', 'Supervisor', 0, 'national', TRUE),
  ('External Lighting', 'Electrician', 0, 'national', TRUE),
  ('External Lighting', 'Civils operative', 0, 'national', TRUE),
  ('External Lighting', 'Plant operator', 0, 'national', TRUE),
  ('External Lighting', 'Supervisor', 0, 'national', TRUE),
  ('Signage', 'Sign installer', 0, 'national', TRUE),
  ('Signage', 'Fabricator', 0, 'national', TRUE),
  ('Signage', 'Electrician', 0, 'national', TRUE),
  ('Signage', 'General operative', 0, 'national', TRUE),
  ('Fencing & Gates', 'Fencer', 0, 'national', TRUE),
  ('Fencing & Gates', 'Groundworker', 0, 'national', TRUE),
  ('Fencing & Gates', 'Welder', 0, 'national', TRUE),
  ('Fencing & Gates', 'Labourer', 0, 'national', TRUE),
  ('Swimming Pools & Water Features', 'Pool installer', 0, 'national', TRUE),
  ('Swimming Pools & Water Features', 'Groundworker', 0, 'national', TRUE),
  ('Swimming Pools & Water Features', 'Steel fixer', 0, 'national', TRUE),
  ('Swimming Pools & Water Features', 'Concrete operative', 0, 'national', TRUE),
  ('Swimming Pools & Water Features', 'Tiler', 0, 'national', TRUE),
  ('Swimming Pools & Water Features', 'Waterproofing operative', 0, 'national', TRUE),
  ('Swimming Pools & Water Features', 'Plumber', 0, 'national', TRUE),
  ('Swimming Pools & Water Features', 'Electrician', 0, 'national', TRUE),
  ('Domestic Electrical', 'Electrician', 0, 'national', TRUE),
  ('Domestic Electrical', 'Approved electrician', 0, 'national', TRUE),
  ('Domestic Electrical', 'Electrical mate', 0, 'national', TRUE),
  ('Domestic Electrical', 'Test engineer', 0, 'national', TRUE),
  ('Commercial Electrical', 'Electrician', 0, 'national', TRUE),
  ('Commercial Electrical', 'Approved electrician', 0, 'national', TRUE),
  ('Commercial Electrical', 'Electrical improver', 0, 'national', TRUE),
  ('Commercial Electrical', 'Mate', 0, 'national', TRUE),
  ('Commercial Electrical', 'Supervisor', 0, 'national', TRUE),
  ('Industrial Electrical', 'Industrial electrician', 0, 'national', TRUE),
  ('Industrial Electrical', 'Cable jointer', 0, 'national', TRUE),
  ('Industrial Electrical', 'Instrument technician', 0, 'national', TRUE),
  ('Industrial Electrical', 'Panel wireman', 0, 'national', TRUE),
  ('Industrial Electrical', 'Supervisor', 0, 'national', TRUE),
  ('EV Chargers', 'EV charge point installer', 0, 'national', TRUE),
  ('EV Chargers', 'Electrician', 0, 'national', TRUE),
  ('EV Chargers', 'Groundworker', 0, 'national', TRUE),
  ('EV Chargers', 'Civils operative', 0, 'national', TRUE),
  ('Street Electrical / Feeder Pillars', 'Electrician', 0, 'national', TRUE),
  ('Street Electrical / Feeder Pillars', 'Utilities operative', 0, 'national', TRUE),
  ('Street Electrical / Feeder Pillars', 'Civils operative', 0, 'national', TRUE),
  ('Street Electrical / Feeder Pillars', 'Supervisor', 0, 'national', TRUE),
  ('Substations', 'HV electrician', 0, 'national', TRUE),
  ('Substations', 'Cable jointer', 0, 'national', TRUE),
  ('Substations', 'Fitter', 0, 'national', TRUE),
  ('Substations', 'Civils operative', 0, 'national', TRUE),
  ('Substations', 'Supervisor', 0, 'national', TRUE),
  ('Domestic Plumbing', 'Plumber', 0, 'national', TRUE),
  ('Domestic Plumbing', 'Plumber’s mate', 0, 'national', TRUE),
  ('Domestic Plumbing', 'Heating engineer', 0, 'national', TRUE),
  ('Commercial Plumbing / Public Health', 'Plumber', 0, 'national', TRUE),
  ('Commercial Plumbing / Public Health', 'Pipefitter', 0, 'national', TRUE),
  ('Commercial Plumbing / Public Health', 'Public health engineer', 0, 'national', TRUE),
  ('Commercial Plumbing / Public Health', 'Mate', 0, 'national', TRUE),
  ('Commercial Plumbing / Public Health', 'Supervisor', 0, 'national', TRUE),
  ('Mechanical / HVAC', 'Mechanical fitter', 0, 'national', TRUE),
  ('Mechanical / HVAC', 'HVAC installer', 0, 'national', TRUE),
  ('Mechanical / HVAC', 'Duct fitter', 0, 'national', TRUE),
  ('Mechanical / HVAC', 'Pipefitter', 0, 'national', TRUE),
  ('Mechanical / HVAC', 'Mate', 0, 'national', TRUE),
  ('Mechanical / HVAC', 'Supervisor', 0, 'national', TRUE),
  ('Domestic Heating', 'Heating engineer', 0, 'national', TRUE),
  ('Domestic Heating', 'Gas Safe engineer', 0, 'national', TRUE),
  ('Domestic Heating', 'Plumber', 0, 'national', TRUE),
  ('Air Conditioning / Refrigeration', 'AC installer', 0, 'national', TRUE),
  ('Air Conditioning / Refrigeration', 'Refrigeration engineer', 0, 'national', TRUE),
  ('Air Conditioning / Refrigeration', 'Electrician', 0, 'national', TRUE),
  ('Air Conditioning / Refrigeration', 'Mate', 0, 'national', TRUE),
  ('Fire Alarm & Life Safety', 'Fire alarm engineer', 0, 'national', TRUE),
  ('Fire Alarm & Life Safety', 'Electrician', 0, 'national', TRUE),
  ('Fire Alarm & Life Safety', 'Commissioning engineer', 0, 'national', TRUE),
  ('Security / CCTV / Access Control', 'Security engineer', 0, 'national', TRUE),
  ('Security / CCTV / Access Control', 'Electrician', 0, 'national', TRUE),
  ('Security / CCTV / Access Control', 'Data installer', 0, 'national', TRUE),
  ('Drylining & Partitions', 'Dryliner', 0, 'national', TRUE),
  ('Drylining & Partitions', 'Ceiling fixer', 0, 'national', TRUE),
  ('Drylining & Partitions', 'Partition fixer', 0, 'national', TRUE),
  ('Drylining & Partitions', 'Labourer', 0, 'national', TRUE),
  ('Plastering & Rendering', 'Plasterer', 0, 'national', TRUE),
  ('Plastering & Rendering', 'Renderer', 0, 'national', TRUE),
  ('Plastering & Rendering', 'Labourer', 0, 'national', TRUE),
  ('Carpentry & Joinery', 'Carpenter', 0, 'national', TRUE),
  ('Carpentry & Joinery', 'Joiner', 0, 'national', TRUE),
  ('Carpentry & Joinery', 'Bench joiner', 0, 'national', TRUE),
  ('Kitchen Installation', 'Kitchen fitter', 0, 'national', TRUE),
  ('Kitchen Installation', 'Carpenter', 0, 'national', TRUE),
  ('Kitchen Installation', 'Plumber', 0, 'national', TRUE),
  ('Kitchen Installation', 'Electrician', 0, 'national', TRUE),
  ('Bathroom Installation', 'Bathroom fitter', 0, 'national', TRUE),
  ('Bathroom Installation', 'Plumber', 0, 'national', TRUE),
  ('Bathroom Installation', 'Tiler', 0, 'national', TRUE),
  ('Bathroom Installation', 'Electrician', 0, 'national', TRUE),
  ('Tiling', 'Tiler', 0, 'national', TRUE),
  ('Tiling', 'Labourer', 0, 'national', TRUE),
  ('Flooring', 'Floor layer', 0, 'national', TRUE),
  ('Flooring', 'Carpet fitter', 0, 'national', TRUE),
  ('Flooring', 'Vinyl installer', 0, 'national', TRUE),
  ('Flooring', 'Wood floor installer', 0, 'national', TRUE),
  ('Ceilings', 'Ceiling fixer', 0, 'national', TRUE),
  ('Ceilings', 'Dryliner', 0, 'national', TRUE),
  ('Ceilings', 'Labourer', 0, 'national', TRUE),
  ('Painting & Decorating', 'Painter and decorator', 0, 'national', TRUE),
  ('Painting & Decorating', 'Spray painter', 0, 'national', TRUE),
  ('Painting & Decorating', 'Paperhanger', 0, 'national', TRUE),
  ('Fire Stopping', 'Fire stopping operative', 0, 'national', TRUE),
  ('Fire Stopping', 'Dryliner', 0, 'national', TRUE),
  ('Fire Stopping', 'Supervisor', 0, 'national', TRUE),
  ('Passive Fire Protection / Intumescent', 'Intumescent applicator', 0, 'national', TRUE),
  ('Passive Fire Protection / Intumescent', 'Painter', 0, 'national', TRUE),
  ('Passive Fire Protection / Intumescent', 'Supervisor', 0, 'national', TRUE),
  ('Diamond Drilling & Sawing', 'Diamond driller', 0, 'national', TRUE),
  ('Diamond Drilling & Sawing', 'Saw operative', 0, 'national', TRUE),
  ('Diamond Drilling & Sawing', 'Labourer', 0, 'national', TRUE),
  ('Builderswork in Connection', 'General builder', 0, 'national', TRUE),
  ('Builderswork in Connection', 'Labourer', 0, 'national', TRUE),
  ('Builderswork in Connection', 'Carpenter', 0, 'national', TRUE),
  ('Builderswork in Connection', 'Groundworker', 0, 'national', TRUE),
  ('Specialist Finishes', 'Specialist finisher', 0, 'national', TRUE),
  ('Specialist Finishes', 'Resin flooring operative', 0, 'national', TRUE),
  ('Specialist Finishes', 'Plaster artisan', 0, 'national', TRUE),
  ('Waste Management / Logistics', 'Site labourer', 0, 'national', TRUE),
  ('Waste Management / Logistics', 'Traffic marshal', 0, 'national', TRUE),
  ('Waste Management / Logistics', 'Gateman', 0, 'national', TRUE),
  ('Waste Management / Logistics', 'Storeman', 0, 'national', TRUE),
  ('Waste Management / Logistics', 'Supervisor', 0, 'national', TRUE) ON CONFLICT DO NOTHING;

-- PLANT (276 items)
-- Nullify FK references from estimate_lines before deleting system defaults
UPDATE estimate_lines SET cost_library_item_id = NULL WHERE cost_library_item_id IN (SELECT id FROM cost_library_items WHERE category = 'Plant' AND is_system_default = TRUE);
DELETE FROM cost_library_items WHERE category = 'Plant' AND is_system_default = TRUE;
INSERT INTO cost_library_items (code, description, unit, base_rate, category, is_system_default) VALUES
  ('PL-0001', 'Welfare unit', 'day', 0, 'Plant', TRUE),
  ('PL-0002', 'Site toilets', 'day', 0, 'Plant', TRUE),
  ('PL-0003', 'Temporary fencing', 'day', 0, 'Plant', TRUE),
  ('PL-0004', 'Temporary lighting', 'day', 0, 'Plant', TRUE),
  ('PL-0005', 'Generator', 'day', 0, 'Plant', TRUE),
  ('PL-0006', 'Water bowser', 'day', 0, 'Plant', TRUE),
  ('PL-0007', 'Site cabins', 'day', 0, 'Plant', TRUE),
  ('PL-0008', 'Pedestrian barriers', 'day', 0, 'Plant', TRUE),
  ('PL-0009', 'Excavator with breaker', 'day', 0, 'Plant', TRUE),
  ('PL-0010', 'Skid steer', 'day', 0, 'Plant', TRUE),
  ('PL-0011', 'Breaker', 'day', 0, 'Plant', TRUE),
  ('PL-0012', 'Floor saw', 'day', 0, 'Plant', TRUE),
  ('PL-0013', 'Dust suppression unit', 'day', 0, 'Plant', TRUE),
  ('PL-0014', 'Grab lorry', 'day', 0, 'Plant', TRUE),
  ('PL-0015', 'Waste chute', 'day', 0, 'Plant', TRUE),
  ('PL-0016', 'Crusher bucket', 'day', 0, 'Plant', TRUE),
  ('PL-0017', 'Mini dumper', 'day', 0, 'Plant', TRUE),
  ('PL-0018', 'Negative pressure unit', 'day', 0, 'Plant', TRUE),
  ('PL-0019', 'H-class vacuum', 'day', 0, 'Plant', TRUE),
  ('PL-0020', 'Decontamination unit', 'day', 0, 'Plant', TRUE),
  ('PL-0021', 'Air monitoring pump', 'day', 0, 'Plant', TRUE),
  ('PL-0022', 'Enclosure equipment', 'day', 0, 'Plant', TRUE),
  ('PL-0023', 'Acrow props', 'day', 0, 'Plant', TRUE),
  ('PL-0024', 'Strongboys', 'day', 0, 'Plant', TRUE),
  ('PL-0025', 'Needle beams', 'day', 0, 'Plant', TRUE),
  ('PL-0026', 'Mini crane', 'day', 0, 'Plant', TRUE),
  ('PL-0027', 'Genie lift', 'day', 0, 'Plant', TRUE),
  ('PL-0028', 'Torque wrench', 'day', 0, 'Plant', TRUE),
  ('PL-0029', 'Mini excavator', 'day', 0, 'Plant', TRUE),
  ('PL-0030', '5t excavator', 'day', 0, 'Plant', TRUE),
  ('PL-0031', '8t excavator', 'day', 0, 'Plant', TRUE),
  ('PL-0032', 'Dumper', 'day', 0, 'Plant', TRUE),
  ('PL-0033', 'Roller', 'day', 0, 'Plant', TRUE),
  ('PL-0034', 'Plate compactor', 'day', 0, 'Plant', TRUE),
  ('PL-0035', 'Laser level', 'day', 0, 'Plant', TRUE),
  ('PL-0036', 'Excavator', 'day', 0, 'Plant', TRUE),
  ('PL-0037', 'Pipe laser', 'day', 0, 'Plant', TRUE),
  ('PL-0038', 'Trench box', 'day', 0, 'Plant', TRUE),
  ('PL-0039', 'Water pump', 'day', 0, 'Plant', TRUE),
  ('PL-0040', 'Jetting unit', 'day', 0, 'Plant', TRUE),
  ('PL-0041', 'Pipe cutter', 'day', 0, 'Plant', TRUE),
  ('PL-0042', 'Pipe lifter', 'day', 0, 'Plant', TRUE),
  ('PL-0043', 'Butt fusion machine', 'day', 0, 'Plant', TRUE),
  ('PL-0044', 'Electrofusion machine', 'day', 0, 'Plant', TRUE),
  ('PL-0045', 'Fusion equipment', 'day', 0, 'Plant', TRUE),
  ('PL-0046', 'Gas detection equipment', 'day', 0, 'Plant', TRUE),
  ('PL-0047', 'Pipe cutters', 'day', 0, 'Plant', TRUE),
  ('PL-0048', 'Cable drum jack', 'day', 0, 'Plant', TRUE),
  ('PL-0049', 'Cable puller', 'day', 0, 'Plant', TRUE),
  ('PL-0050', 'Duct rodding tools', 'day', 0, 'Plant', TRUE),
  ('PL-0051', 'CAT scanner', 'day', 0, 'Plant', TRUE),
  ('PL-0052', 'Cable pulling equipment', 'day', 0, 'Plant', TRUE),
  ('PL-0053', 'Duct rodder', 'day', 0, 'Plant', TRUE),
  ('PL-0054', 'Mini compressor', 'day', 0, 'Plant', TRUE),
  ('PL-0055', 'Compactor', 'day', 0, 'Plant', TRUE),
  ('PL-0056', 'Pump', 'day', 0, 'Plant', TRUE),
  ('PL-0057', 'Piling rig', 'day', 0, 'Plant', TRUE),
  ('PL-0058', 'Auger', 'day', 0, 'Plant', TRUE),
  ('PL-0059', 'Crane', 'day', 0, 'Plant', TRUE),
  ('PL-0060', 'Concrete pump', 'day', 0, 'Plant', TRUE),
  ('PL-0061', 'Tremie equipment', 'day', 0, 'Plant', TRUE),
  ('PL-0062', 'Concrete mixer', 'day', 0, 'Plant', TRUE),
  ('PL-0063', 'Props', 'day', 0, 'Plant', TRUE),
  ('PL-0064', 'Needles', 'day', 0, 'Plant', TRUE),
  ('PL-0065', 'Concrete poker', 'day', 0, 'Plant', TRUE),
  ('PL-0066', 'Power float', 'day', 0, 'Plant', TRUE),
  ('PL-0067', 'Formwork system', 'day', 0, 'Plant', TRUE),
  ('PL-0068', 'Concrete skip', 'day', 0, 'Plant', TRUE),
  ('PL-0069', 'Mobile crane', 'day', 0, 'Plant', TRUE),
  ('PL-0070', 'Telehandler', 'day', 0, 'Plant', TRUE),
  ('PL-0071', 'MEWP', 'day', 0, 'Plant', TRUE),
  ('PL-0072', 'Welder', 'day', 0, 'Plant', TRUE),
  ('PL-0073', 'Mag drill', 'day', 0, 'Plant', TRUE),
  ('PL-0074', 'Nail gun', 'day', 0, 'Plant', TRUE),
  ('PL-0075', 'Mitre saw', 'day', 0, 'Plant', TRUE),
  ('PL-0076', 'Circular saw', 'day', 0, 'Plant', TRUE),
  ('PL-0077', 'Mortar mixer', 'day', 0, 'Plant', TRUE),
  ('PL-0078', 'Brick saw', 'day', 0, 'Plant', TRUE),
  ('PL-0079', 'Hoist', 'day', 0, 'Plant', TRUE),
  ('PL-0080', 'Hop-ups', 'day', 0, 'Plant', TRUE),
  ('PL-0081', 'Rivet tools', 'day', 0, 'Plant', TRUE),
  ('PL-0082', 'Drill set', 'day', 0, 'Plant', TRUE),
  ('PL-0083', 'Tile hoist', 'day', 0, 'Plant', TRUE),
  ('PL-0084', 'Roof ladder', 'day', 0, 'Plant', TRUE),
  ('PL-0085', 'Scaffold access', 'day', 0, 'Plant', TRUE),
  ('PL-0086', 'Hot air welder', 'day', 0, 'Plant', TRUE),
  ('PL-0087', 'Torch-on kit', 'day', 0, 'Plant', TRUE),
  ('PL-0088', 'Rollers', 'day', 0, 'Plant', TRUE),
  ('PL-0089', 'Spray equipment', 'day', 0, 'Plant', TRUE),
  ('PL-0090', 'Insulation blower', 'day', 0, 'Plant', TRUE),
  ('PL-0091', 'Staple gun', 'day', 0, 'Plant', TRUE),
  ('PL-0092', 'Board saw', 'day', 0, 'Plant', TRUE),
  ('PL-0093', 'Tower scaffold', 'day', 0, 'Plant', TRUE),
  ('PL-0094', 'Glass lifter', 'day', 0, 'Plant', TRUE),
  ('PL-0095', 'Mixer', 'day', 0, 'Plant', TRUE),
  ('PL-0096', 'SDS drill', 'day', 0, 'Plant', TRUE),
  ('PL-0097', 'Rotavator', 'day', 0, 'Plant', TRUE),
  ('PL-0098', 'Turf cutter', 'day', 0, 'Plant', TRUE),
  ('PL-0099', 'Road saw', 'day', 0, 'Plant', TRUE),
  ('PL-0100', 'Paver tools', 'day', 0, 'Plant', TRUE),
  ('PL-0101', 'Hot box', 'day', 0, 'Plant', TRUE),
  ('PL-0102', 'Line marker machine', 'day', 0, 'Plant', TRUE),
  ('PL-0103', 'Thermoplastic applicator', 'day', 0, 'Plant', TRUE),
  ('PL-0104', 'Compressor', 'day', 0, 'Plant', TRUE),
  ('PL-0105', 'Fixing tools', 'day', 0, 'Plant', TRUE),
  ('PL-0106', 'Post hole auger', 'day', 0, 'Plant', TRUE),
  ('PL-0107', 'Poker', 'day', 0, 'Plant', TRUE),
  ('PL-0108', 'Tile cutter', 'day', 0, 'Plant', TRUE),
  ('PL-0109', 'Pressure testing kit', 'day', 0, 'Plant', TRUE),
  ('PL-0110', 'Test kit', 'day', 0, 'Plant', TRUE),
  ('PL-0111', 'Cable rods', 'day', 0, 'Plant', TRUE),
  ('PL-0112', 'Core drill', 'day', 0, 'Plant', TRUE),
  ('PL-0113', 'Step ladders', 'day', 0, 'Plant', TRUE),
  ('PL-0114', 'Cable drum jacks', 'day', 0, 'Plant', TRUE),
  ('PL-0115', 'Testing gear', 'day', 0, 'Plant', TRUE),
  ('PL-0116', 'Cable winch', 'day', 0, 'Plant', TRUE),
  ('PL-0117', 'Test gear', 'day', 0, 'Plant', TRUE),
  ('PL-0118', 'Crimp tools', 'day', 0, 'Plant', TRUE),
  ('PL-0119', 'Test equipment', 'day', 0, 'Plant', TRUE),
  ('PL-0120', 'Excavation plant', 'day', 0, 'Plant', TRUE),
  ('PL-0121', 'Lifting equipment', 'day', 0, 'Plant', TRUE),
  ('PL-0122', 'Press tool', 'day', 0, 'Plant', TRUE),
  ('PL-0123', 'Pipe bender', 'day', 0, 'Plant', TRUE),
  ('PL-0124', 'Test pump', 'day', 0, 'Plant', TRUE),
  ('PL-0125', 'Press tools', 'day', 0, 'Plant', TRUE),
  ('PL-0126', 'Threader', 'day', 0, 'Plant', TRUE),
  ('PL-0127', 'Welding equipment', 'day', 0, 'Plant', TRUE),
  ('PL-0128', 'Threading machine', 'day', 0, 'Plant', TRUE),
  ('PL-0129', 'Press-fit tools', 'day', 0, 'Plant', TRUE),
  ('PL-0130', 'Flue gas analyser', 'day', 0, 'Plant', TRUE),
  ('PL-0131', 'Vacuum pump', 'day', 0, 'Plant', TRUE),
  ('PL-0132', 'Refrigerant gauges', 'day', 0, 'Plant', TRUE),
  ('PL-0133', 'Access tower', 'day', 0, 'Plant', TRUE),
  ('PL-0134', 'Access equipment', 'day', 0, 'Plant', TRUE),
  ('PL-0135', 'Test meter', 'day', 0, 'Plant', TRUE),
  ('PL-0136', 'Cable pulling tools', 'day', 0, 'Plant', TRUE),
  ('PL-0137', 'Board lifter', 'day', 0, 'Plant', TRUE),
  ('PL-0138', 'Screw gun', 'day', 0, 'Plant', TRUE),
  ('PL-0139', 'Spray machine', 'day', 0, 'Plant', TRUE),
  ('PL-0140', 'Router', 'day', 0, 'Plant', TRUE),
  ('PL-0141', 'Sander', 'day', 0, 'Plant', TRUE),
  ('PL-0142', 'Worktop jig', 'day', 0, 'Plant', TRUE),
  ('PL-0143', 'Wet saw', 'day', 0, 'Plant', TRUE),
  ('PL-0144', 'Mixer drill', 'day', 0, 'Plant', TRUE),
  ('PL-0145', 'Floor grinder', 'day', 0, 'Plant', TRUE),
  ('PL-0146', 'Saw', 'day', 0, 'Plant', TRUE),
  ('PL-0147', 'Floor stripper', 'day', 0, 'Plant', TRUE),
  ('PL-0148', 'Sprayer', 'day', 0, 'Plant', TRUE),
  ('PL-0149', 'Sealant guns', 'day', 0, 'Plant', TRUE),
  ('PL-0150', 'Dry film thickness gauge', 'day', 0, 'Plant', TRUE),
  ('PL-0151', 'Wall saw', 'day', 0, 'Plant', TRUE),
  ('PL-0152', 'Track saw', 'day', 0, 'Plant', TRUE),
  ('PL-0153', 'Water suppression', 'day', 0, 'Plant', TRUE),
  ('PL-0154', 'Drill', 'day', 0, 'Plant', TRUE),
  ('PL-0155', 'Skip', 'day', 0, 'Plant', TRUE),
  ('PL-0156', 'Forklift', 'day', 0, 'Plant', TRUE) ON CONFLICT DO NOTHING;

-- MATERIALS (502 items)
-- Nullify FK references from estimate_lines before deleting system defaults
UPDATE estimate_lines SET cost_library_item_id = NULL WHERE cost_library_item_id IN (SELECT id FROM cost_library_items WHERE is_system_default = TRUE AND category NOT IN ('Plant','Labour','Preliminaries','Subcontract','Consultancy','Provisional Sums'));
DELETE FROM cost_library_items WHERE is_system_default = TRUE AND category NOT IN ('Plant','Labour','Preliminaries','Subcontract','Consultancy','Provisional Sums');
INSERT INTO cost_library_items (code, description, unit, base_rate, category, is_system_default) VALUES
  ('MAT-0001', 'Heras fencing', 'nr', 0, 'Site Setup & Preliminaries', TRUE),
  ('MAT-0002', 'Fence blocks', 'nr', 0, 'Site Setup & Preliminaries', TRUE),
  ('MAT-0003', 'Warning signage', 'nr', 0, 'Site Setup & Preliminaries', TRUE),
  ('MAT-0004', 'Temporary hoarding', 'nr', 0, 'Site Setup & Preliminaries', TRUE),
  ('MAT-0005', 'Protection boards', 'nr', 0, 'Site Setup & Preliminaries', TRUE),
  ('MAT-0006', 'Temporary power leads', 'nr', 0, 'Site Setup & Preliminaries', TRUE),
  ('MAT-0007', 'Temporary lighting strings', 'nr', 0, 'Site Setup & Preliminaries', TRUE),
  ('MAT-0008', 'Fuel', 'nr', 0, 'Site Setup & Preliminaries', TRUE),
  ('MAT-0009', 'Sandbags', 'nr', 0, 'Site Setup & Preliminaries', TRUE),
  ('MAT-0010', 'Ply sheets', 'nr', 0, 'Site Setup & Preliminaries', TRUE),
  ('MAT-0011', 'Dust sheets', 'nr', 0, 'Demolition & Strip Out', TRUE),
  ('MAT-0012', 'Polythene sheeting', 'nr', 0, 'Demolition & Strip Out', TRUE),
  ('MAT-0013', 'Debris bags', 'nr', 0, 'Demolition & Strip Out', TRUE),
  ('MAT-0014', 'Warning tape', 'nr', 0, 'Demolition & Strip Out', TRUE),
  ('MAT-0015', 'Temporary propping consumables', 'nr', 0, 'Demolition & Strip Out', TRUE),
  ('MAT-0016', 'Skip liners', 'nr', 0, 'Demolition & Strip Out', TRUE),
  ('MAT-0017', 'Warning labels', 'nr', 0, 'Asbestos Removal', TRUE),
  ('MAT-0018', 'Disposal bags', 'nr', 0, 'Asbestos Removal', TRUE),
  ('MAT-0019', 'Duct tape', 'nr', 0, 'Asbestos Removal', TRUE),
  ('MAT-0020', 'Transit wrapping', 'nr', 0, 'Asbestos Removal', TRUE),
  ('MAT-0021', 'PPE consumables', 'nr', 0, 'Asbestos Removal', TRUE),
  ('MAT-0022', 'Acrow props', 'nr', 0, 'Temporary Works / Propping / Shoring', TRUE),
  ('MAT-0023', 'Timber needles', 'nr', 0, 'Temporary Works / Propping / Shoring', TRUE),
  ('MAT-0024', 'Steel channels', 'nr', 0, 'Temporary Works / Propping / Shoring', TRUE),
  ('MAT-0025', 'Sole plates', 'nr', 0, 'Temporary Works / Propping / Shoring', TRUE),
  ('MAT-0026', 'Packers', 'nr', 0, 'Temporary Works / Propping / Shoring', TRUE),
  ('MAT-0027', 'Fixings', 'nr', 0, 'Temporary Works / Propping / Shoring', TRUE),
  ('MAT-0028', 'Resin anchors', 'nr', 0, 'Temporary Works / Propping / Shoring', TRUE),
  ('MAT-0029', 'Type 1 MOT', 'nr', 0, 'Groundworks & Civils', TRUE),
  ('MAT-0030', '6F2 fill', 'nr', 0, 'Groundworks & Civils', TRUE),
  ('MAT-0031', 'Sharp sand', 'nr', 0, 'Groundworks & Civils', TRUE),
  ('MAT-0032', 'Blinding', 'nr', 0, 'Groundworks & Civils', TRUE),
  ('MAT-0033', 'Geotextile membrane', 'nr', 0, 'Groundworks & Civils', TRUE),
  ('MAT-0034', 'DPM', 'nr', 0, 'Groundworks & Civils', TRUE),
  ('MAT-0035', 'Mesh reinforcement', 'nr', 0, 'Groundworks & Civils', TRUE),
  ('MAT-0036', 'Timber for formwork', 'nr', 0, 'Groundworks & Civils', TRUE),
  ('MAT-0037', '110mm uPVC pipe', 'nr', 0, 'Drainage', TRUE),
  ('MAT-0038', '160mm uPVC pipe', 'nr', 0, 'Drainage', TRUE),
  ('MAT-0039', 'Twinwall pipe', 'nr', 0, 'Drainage', TRUE),
  ('MAT-0040', 'Bends', 'nr', 0, 'Drainage', TRUE),
  ('MAT-0041', 'Junctions', 'nr', 0, 'Drainage', TRUE),
  ('MAT-0042', 'Gullies', 'nr', 0, 'Drainage', TRUE),
  ('MAT-0043', 'Inspection chambers', 'nr', 0, 'Drainage', TRUE),
  ('MAT-0044', 'Covers and frames', 'nr', 0, 'Drainage', TRUE),
  ('MAT-0045', 'Concrete rings', 'nr', 0, 'Drainage', TRUE),
  ('MAT-0046', 'Bedding material', 'nr', 0, 'Drainage', TRUE),
  ('MAT-0047', 'MDPE water pipe', 'nr', 0, 'Utilities – Water', TRUE),
  ('MAT-0048', 'Ductile iron pipe', 'nr', 0, 'Utilities – Water', TRUE),
  ('MAT-0049', 'Valves', 'nr', 0, 'Utilities – Water', TRUE),
  ('MAT-0050', 'Hydrants', 'nr', 0, 'Utilities – Water', TRUE),
  ('MAT-0051', 'Service connections', 'nr', 0, 'Utilities – Water', TRUE),
  ('MAT-0052', 'Electrofusion couplers', 'nr', 0, 'Utilities – Water', TRUE),
  ('MAT-0053', 'Marker tape', 'nr', 0, 'Utilities – Water', TRUE),
  ('MAT-0054', 'Bedding stone', 'nr', 0, 'Utilities – Water', TRUE),
  ('MAT-0055', 'PE gas pipe', 'nr', 0, 'Utilities – Gas', TRUE),
  ('MAT-0056', 'Service tees', 'nr', 0, 'Utilities – Gas', TRUE),
  ('MAT-0057', 'Warning tiles', 'nr', 0, 'Utilities – Gas', TRUE),
  ('MAT-0058', 'Tracer wire', 'nr', 0, 'Utilities – Gas', TRUE),
  ('MAT-0059', 'Electric ducting', 'nr', 0, 'Utilities – Electric / Ducting', TRUE),
  ('MAT-0060', 'Draw rope', 'nr', 0, 'Utilities – Electric / Ducting', TRUE),
  ('MAT-0061', 'Cable pits', 'nr', 0, 'Utilities – Electric / Ducting', TRUE),
  ('MAT-0062', 'Joint bays', 'nr', 0, 'Utilities – Electric / Ducting', TRUE),
  ('MAT-0063', 'Backfill sand', 'nr', 0, 'Utilities – Electric / Ducting', TRUE),
  ('MAT-0064', 'Concrete protection tiles', 'nr', 0, 'Utilities – Electric / Ducting', TRUE),
  ('MAT-0065', 'Telecom duct', 'nr', 0, 'Utilities – Telecoms / Data Ducting', TRUE),
  ('MAT-0066', 'Sub-duct', 'nr', 0, 'Utilities – Telecoms / Data Ducting', TRUE),
  ('MAT-0067', 'Chambers', 'nr', 0, 'Utilities – Telecoms / Data Ducting', TRUE),
  ('MAT-0068', 'Access covers', 'nr', 0, 'Utilities – Telecoms / Data Ducting', TRUE),
  ('MAT-0069', 'Attenuation crates', 'nr', 0, 'Attenuation / SuDS / Stormwater', TRUE),
  ('MAT-0070', 'Geogrid', 'nr', 0, 'Attenuation / SuDS / Stormwater', TRUE),
  ('MAT-0071', 'Flow control chamber', 'nr', 0, 'Attenuation / SuDS / Stormwater', TRUE),
  ('MAT-0072', 'Hydrobrake', 'nr', 0, 'Attenuation / SuDS / Stormwater', TRUE),
  ('MAT-0073', 'Silt trap', 'nr', 0, 'Attenuation / SuDS / Stormwater', TRUE),
  ('MAT-0074', 'Catch pits', 'nr', 0, 'Attenuation / SuDS / Stormwater', TRUE),
  ('MAT-0075', 'Permeable sub-base', 'nr', 0, 'Attenuation / SuDS / Stormwater', TRUE),
  ('MAT-0076', 'Pipework', 'nr', 0, 'Attenuation / SuDS / Stormwater', TRUE),
  ('MAT-0077', 'Reinforcement cages', 'nr', 0, 'Piling', TRUE),
  ('MAT-0078', 'Concrete', 'nr', 0, 'Piling', TRUE),
  ('MAT-0079', 'Pile casings', 'nr', 0, 'Piling', TRUE),
  ('MAT-0080', 'Bentonite / support fluids', 'nr', 0, 'Piling', TRUE),
  ('MAT-0081', 'Spacer wheels', 'nr', 0, 'Piling', TRUE),
  ('MAT-0082', 'Steel sections', 'nr', 0, 'Piling', TRUE),
  ('MAT-0083', 'Reinforcement', 'nr', 0, 'Underpinning & Structural Stabilisation', TRUE),
  ('MAT-0084', 'Shuttering', 'nr', 0, 'Underpinning & Structural Stabilisation', TRUE),
  ('MAT-0085', 'Engineering brick', 'nr', 0, 'Underpinning & Structural Stabilisation', TRUE),
  ('MAT-0086', 'Structural grout', 'nr', 0, 'Underpinning & Structural Stabilisation', TRUE),
  ('MAT-0087', 'Steel beams', 'nr', 0, 'Underpinning & Structural Stabilisation', TRUE),
  ('MAT-0088', 'Ready-mix concrete', 'nr', 0, 'Concrete / RC Works', TRUE),
  ('MAT-0089', 'Rebar', 'nr', 0, 'Concrete / RC Works', TRUE),
  ('MAT-0090', 'Mesh', 'nr', 0, 'Concrete / RC Works', TRUE),
  ('MAT-0091', 'Formwork plywood', 'nr', 0, 'Concrete / RC Works', TRUE),
  ('MAT-0092', 'Timber studs', 'nr', 0, 'Concrete / RC Works', TRUE),
  ('MAT-0093', 'Release agent', 'nr', 0, 'Concrete / RC Works', TRUE),
  ('MAT-0094', 'Waterbar', 'nr', 0, 'Concrete / RC Works', TRUE),
  ('MAT-0095', 'Curing compound', 'nr', 0, 'Concrete / RC Works', TRUE),
  ('MAT-0096', 'Joint filler', 'nr', 0, 'Concrete / RC Works', TRUE),
  ('MAT-0097', 'UB sections', 'nr', 0, 'Steel Frame / Steel Erection', TRUE),
  ('MAT-0098', 'UC sections', 'nr', 0, 'Steel Frame / Steel Erection', TRUE),
  ('MAT-0099', 'RHS sections', 'nr', 0, 'Steel Frame / Steel Erection', TRUE),
  ('MAT-0100', 'SHS sections', 'nr', 0, 'Steel Frame / Steel Erection', TRUE),
  ('MAT-0101', 'Plates', 'nr', 0, 'Steel Frame / Steel Erection', TRUE),
  ('MAT-0102', 'Holding down bolts', 'nr', 0, 'Steel Frame / Steel Erection', TRUE),
  ('MAT-0103', 'HSFG bolts', 'nr', 0, 'Steel Frame / Steel Erection', TRUE),
  ('MAT-0104', 'Shims', 'nr', 0, 'Steel Frame / Steel Erection', TRUE),
  ('MAT-0105', 'Intumescent paint', 'nr', 0, 'Steel Frame / Steel Erection', TRUE),
  ('MAT-0106', 'Primer', 'nr', 0, 'Steel Frame / Steel Erection', TRUE),
  ('MAT-0107', 'C24 timber', 'nr', 0, 'Structural Timber / Framing', TRUE),
  ('MAT-0108', 'Stud timber', 'nr', 0, 'Structural Timber / Framing', TRUE),
  ('MAT-0109', 'I-joists', 'nr', 0, 'Structural Timber / Framing', TRUE),
  ('MAT-0110', 'Metal web joists', 'nr', 0, 'Structural Timber / Framing', TRUE),
  ('MAT-0111', 'OSB', 'nr', 0, 'Structural Timber / Framing', TRUE),
  ('MAT-0112', 'Sheathing board', 'nr', 0, 'Structural Timber / Framing', TRUE),
  ('MAT-0113', 'Joist hangers', 'nr', 0, 'Structural Timber / Framing', TRUE),
  ('MAT-0114', 'Breather membrane', 'nr', 0, 'Structural Timber / Framing', TRUE),
  ('MAT-0115', 'Structural screws', 'nr', 0, 'Structural Timber / Framing', TRUE),
  ('MAT-0116', 'Facing brick', 'nr', 0, 'Masonry / Brickwork / Blockwork', TRUE),
  ('MAT-0117', 'Concrete block', 'nr', 0, 'Masonry / Brickwork / Blockwork', TRUE),
  ('MAT-0118', 'Aircrete block', 'nr', 0, 'Masonry / Brickwork / Blockwork', TRUE),
  ('MAT-0119', 'Sand', 'nr', 0, 'Masonry / Brickwork / Blockwork', TRUE),
  ('MAT-0120', 'Cement', 'nr', 0, 'Masonry / Brickwork / Blockwork', TRUE),
  ('MAT-0121', 'Lime', 'nr', 0, 'Masonry / Brickwork / Blockwork', TRUE),
  ('MAT-0122', 'DPC', 'nr', 0, 'Masonry / Brickwork / Blockwork', TRUE),
  ('MAT-0123', 'Wall ties', 'nr', 0, 'Masonry / Brickwork / Blockwork', TRUE),
  ('MAT-0124', 'Lintels', 'nr', 0, 'Masonry / Brickwork / Blockwork', TRUE),
  ('MAT-0125', 'Cavity trays', 'nr', 0, 'Masonry / Brickwork / Blockwork', TRUE),
  ('MAT-0126', 'Aluminium cladding panels', 'nr', 0, 'Cladding & Rainscreen', TRUE),
  ('MAT-0127', 'Composite panels', 'nr', 0, 'Cladding & Rainscreen', TRUE),
  ('MAT-0128', 'Fibre cement boards', 'nr', 0, 'Cladding & Rainscreen', TRUE),
  ('MAT-0129', 'Carrier rails', 'nr', 0, 'Cladding & Rainscreen', TRUE),
  ('MAT-0130', 'Brackets', 'nr', 0, 'Cladding & Rainscreen', TRUE),
  ('MAT-0131', 'Insulation', 'nr', 0, 'Cladding & Rainscreen', TRUE),
  ('MAT-0132', 'Fire barriers', 'nr', 0, 'Cladding & Rainscreen', TRUE),
  ('MAT-0133', 'Rivets', 'nr', 0, 'Cladding & Rainscreen', TRUE),
  ('MAT-0134', 'Flashings', 'nr', 0, 'Cladding & Rainscreen', TRUE),
  ('MAT-0135', 'Roof tiles', 'nr', 0, 'Roofing', TRUE),
  ('MAT-0136', 'Slate', 'nr', 0, 'Roofing', TRUE),
  ('MAT-0137', 'Battens', 'nr', 0, 'Roofing', TRUE),
  ('MAT-0138', 'Membrane', 'nr', 0, 'Roofing', TRUE),
  ('MAT-0139', 'Felt', 'nr', 0, 'Roofing', TRUE),
  ('MAT-0140', 'EPDM', 'nr', 0, 'Roofing', TRUE),
  ('MAT-0141', 'Single ply', 'nr', 0, 'Roofing', TRUE),
  ('MAT-0142', 'Lead flashing', 'nr', 0, 'Roofing', TRUE),
  ('MAT-0143', 'Ridge system', 'nr', 0, 'Roofing', TRUE),
  ('MAT-0144', 'Gutter', 'nr', 0, 'Roofing', TRUE),
  ('MAT-0145', 'Downpipe', 'nr', 0, 'Roofing', TRUE),
  ('MAT-0146', 'Roof insulation', 'nr', 0, 'Roofing', TRUE),
  ('MAT-0147', 'Tanking slurry', 'nr', 0, 'Waterproofing', TRUE),
  ('MAT-0148', 'Liquid waterproofing', 'nr', 0, 'Waterproofing', TRUE),
  ('MAT-0149', 'Bituminous membrane', 'nr', 0, 'Waterproofing', TRUE),
  ('MAT-0150', 'Torch-on felt', 'nr', 0, 'Waterproofing', TRUE),
  ('MAT-0151', 'EPDM membrane', 'nr', 0, 'Waterproofing', TRUE),
  ('MAT-0152', 'Protection board', 'nr', 0, 'Waterproofing', TRUE),
  ('MAT-0153', 'Waterstops', 'nr', 0, 'Waterproofing', TRUE),
  ('MAT-0154', 'Drainage boards', 'nr', 0, 'Waterproofing', TRUE),
  ('MAT-0155', 'Mineral wool', 'nr', 0, 'Insulation', TRUE),
  ('MAT-0156', 'PIR board', 'nr', 0, 'Insulation', TRUE),
  ('MAT-0157', 'Acoustic slab', 'nr', 0, 'Insulation', TRUE),
  ('MAT-0158', 'Loft roll', 'nr', 0, 'Insulation', TRUE),
  ('MAT-0159', 'EWI insulation board', 'nr', 0, 'Insulation', TRUE),
  ('MAT-0160', 'VCL', 'nr', 0, 'Insulation', TRUE),
  ('MAT-0161', 'Foil tape', 'nr', 0, 'Insulation', TRUE),
  ('MAT-0162', 'uPVC windows', 'nr', 0, 'Windows, Doors & Glazing', TRUE),
  ('MAT-0163', 'Aluminium windows', 'nr', 0, 'Windows, Doors & Glazing', TRUE),
  ('MAT-0164', 'Composite doors', 'nr', 0, 'Windows, Doors & Glazing', TRUE),
  ('MAT-0165', 'Patio doors', 'nr', 0, 'Windows, Doors & Glazing', TRUE),
  ('MAT-0166', 'Double glazed units', 'nr', 0, 'Windows, Doors & Glazing', TRUE),
  ('MAT-0167', 'Toughened glass', 'nr', 0, 'Windows, Doors & Glazing', TRUE),
  ('MAT-0168', 'Sealant', 'nr', 0, 'Windows, Doors & Glazing', TRUE),
  ('MAT-0169', 'Frame fixings', 'nr', 0, 'Windows, Doors & Glazing', TRUE),
  ('MAT-0170', 'Trickle vents', 'nr', 0, 'Windows, Doors & Glazing', TRUE),
  ('MAT-0171', 'Blocks', 'nr', 0, 'Builders / General Building', TRUE),
  ('MAT-0172', 'Timber', 'nr', 0, 'Builders / General Building', TRUE),
  ('MAT-0173', 'Plasterboard', 'nr', 0, 'Builders / General Building', TRUE),
  ('MAT-0174', 'Sealants', 'nr', 0, 'Builders / General Building', TRUE),
  ('MAT-0175', 'General sundries', 'nr', 0, 'Builders / General Building', TRUE),
  ('MAT-0176', 'Structural timber', 'nr', 0, 'Loft Conversion / Extension / Domestic Framing', TRUE),
  ('MAT-0177', 'Roof windows', 'nr', 0, 'Loft Conversion / Extension / Domestic Framing', TRUE),
  ('MAT-0178', 'Floorboards', 'nr', 0, 'Loft Conversion / Extension / Domestic Framing', TRUE),
  ('MAT-0179', 'Studwork', 'nr', 0, 'Loft Conversion / Extension / Domestic Framing', TRUE),
  ('MAT-0180', 'Base concrete', 'nr', 0, 'Conservatories / Garden Rooms / Outbuildings', TRUE),
  ('MAT-0181', 'Frame systems', 'nr', 0, 'Conservatories / Garden Rooms / Outbuildings', TRUE),
  ('MAT-0182', 'Roof panels', 'nr', 0, 'Conservatories / Garden Rooms / Outbuildings', TRUE),
  ('MAT-0183', 'Glass units', 'nr', 0, 'Conservatories / Garden Rooms / Outbuildings', TRUE),
  ('MAT-0184', 'Doors', 'nr', 0, 'Conservatories / Garden Rooms / Outbuildings', TRUE),
  ('MAT-0185', 'Cladding', 'nr', 0, 'Conservatories / Garden Rooms / Outbuildings', TRUE),
  ('MAT-0186', 'Turf', 'nr', 0, 'Landscaping & External Works', TRUE),
  ('MAT-0187', 'Topsoil', 'nr', 0, 'Landscaping & External Works', TRUE),
  ('MAT-0188', 'Bark mulch', 'nr', 0, 'Landscaping & External Works', TRUE),
  ('MAT-0189', 'Compost', 'nr', 0, 'Landscaping & External Works', TRUE),
  ('MAT-0190', 'Plants', 'nr', 0, 'Landscaping & External Works', TRUE),
  ('MAT-0191', 'Trees', 'nr', 0, 'Landscaping & External Works', TRUE),
  ('MAT-0192', 'Root barriers', 'nr', 0, 'Landscaping & External Works', TRUE),
  ('MAT-0193', 'Irrigation pipe', 'nr', 0, 'Landscaping & External Works', TRUE),
  ('MAT-0194', 'Decorative gravel', 'nr', 0, 'Landscaping & External Works', TRUE),
  ('MAT-0195', 'Block paving', 'nr', 0, 'Surfacing, Paving & Kerbing', TRUE),
  ('MAT-0196', 'Porcelain paving', 'nr', 0, 'Surfacing, Paving & Kerbing', TRUE),
  ('MAT-0197', 'Sandstone slabs', 'nr', 0, 'Surfacing, Paving & Kerbing', TRUE),
  ('MAT-0198', 'Kerbs', 'nr', 0, 'Surfacing, Paving & Kerbing', TRUE),
  ('MAT-0199', 'Jointing sand', 'nr', 0, 'Surfacing, Paving & Kerbing', TRUE),
  ('MAT-0200', 'Asphalt', 'nr', 0, 'Surfacing, Paving & Kerbing', TRUE),
  ('MAT-0201', 'Tack coat', 'nr', 0, 'Surfacing, Paving & Kerbing', TRUE),
  ('MAT-0202', 'Edging restraint', 'nr', 0, 'Surfacing, Paving & Kerbing', TRUE),
  ('MAT-0203', 'Road marking paint', 'nr', 0, 'Line Marking & Road Furniture', TRUE),
  ('MAT-0204', 'Thermoplastic line material', 'nr', 0, 'Line Marking & Road Furniture', TRUE),
  ('MAT-0205', 'Reflective beads', 'nr', 0, 'Line Marking & Road Furniture', TRUE),
  ('MAT-0206', 'Preformed symbols', 'nr', 0, 'Line Marking & Road Furniture', TRUE),
  ('MAT-0207', 'Bollards', 'nr', 0, 'Line Marking & Road Furniture', TRUE),
  ('MAT-0208', 'Road studs', 'nr', 0, 'Line Marking & Road Furniture', TRUE),
  ('MAT-0209', 'Lighting columns', 'nr', 0, 'External Lighting', TRUE),
  ('MAT-0210', 'Root foundations', 'nr', 0, 'External Lighting', TRUE),
  ('MAT-0211', 'Ducting', 'nr', 0, 'External Lighting', TRUE),
  ('MAT-0212', 'SWA cable', 'nr', 0, 'External Lighting', TRUE),
  ('MAT-0213', 'Feeder pillar', 'nr', 0, 'External Lighting', TRUE),
  ('MAT-0214', 'Lanterns', 'nr', 0, 'External Lighting', TRUE),
  ('MAT-0215', 'Photocells', 'nr', 0, 'External Lighting', TRUE),
  ('MAT-0216', 'Junction boxes', 'nr', 0, 'External Lighting', TRUE),
  ('MAT-0217', 'Sign panels', 'nr', 0, 'Signage', TRUE),
  ('MAT-0218', 'Posts', 'nr', 0, 'Signage', TRUE),
  ('MAT-0219', 'Base plates', 'nr', 0, 'Signage', TRUE),
  ('MAT-0220', 'LED modules', 'nr', 0, 'Signage', TRUE),
  ('MAT-0221', 'Acrylic panels', 'nr', 0, 'Signage', TRUE),
  ('MAT-0222', 'Vinyl graphics', 'nr', 0, 'Signage', TRUE),
  ('MAT-0223', 'Concrete for bases', 'nr', 0, 'Signage', TRUE),
  ('MAT-0224', 'Timber fence panels', 'nr', 0, 'Fencing & Gates', TRUE),
  ('MAT-0225', 'Concrete posts', 'nr', 0, 'Fencing & Gates', TRUE),
  ('MAT-0226', 'Gravel boards', 'nr', 0, 'Fencing & Gates', TRUE),
  ('MAT-0227', 'Chain link fencing', 'nr', 0, 'Fencing & Gates', TRUE),
  ('MAT-0228', 'Mesh fencing', 'nr', 0, 'Fencing & Gates', TRUE),
  ('MAT-0229', 'Gates', 'nr', 0, 'Fencing & Gates', TRUE),
  ('MAT-0230', 'Hinges', 'nr', 0, 'Fencing & Gates', TRUE),
  ('MAT-0231', 'Latches', 'nr', 0, 'Fencing & Gates', TRUE),
  ('MAT-0232', 'Postcrete', 'nr', 0, 'Fencing & Gates', TRUE),
  ('MAT-0233', 'Reinforced concrete', 'nr', 0, 'Swimming Pools & Water Features', TRUE),
  ('MAT-0234', 'Pool shell system', 'nr', 0, 'Swimming Pools & Water Features', TRUE),
  ('MAT-0235', 'Waterproof membrane', 'nr', 0, 'Swimming Pools & Water Features', TRUE),
  ('MAT-0236', 'Pool liner', 'nr', 0, 'Swimming Pools & Water Features', TRUE),
  ('MAT-0237', 'Coping stones', 'nr', 0, 'Swimming Pools & Water Features', TRUE),
  ('MAT-0238', 'Filtration plant', 'nr', 0, 'Swimming Pools & Water Features', TRUE),
  ('MAT-0239', 'Pumps', 'nr', 0, 'Swimming Pools & Water Features', TRUE),
  ('MAT-0240', 'Pool lights', 'nr', 0, 'Swimming Pools & Water Features', TRUE),
  ('MAT-0241', 'Gratings', 'nr', 0, 'Swimming Pools & Water Features', TRUE),
  ('MAT-0242', 'Balance tank components', 'nr', 0, 'Swimming Pools & Water Features', TRUE),
  ('MAT-0243', 'Twin and earth cable', 'nr', 0, 'Domestic Electrical', TRUE),
  ('MAT-0244', 'Consumer unit', 'nr', 0, 'Domestic Electrical', TRUE),
  ('MAT-0245', 'RCBOs', 'nr', 0, 'Domestic Electrical', TRUE),
  ('MAT-0246', 'Sockets', 'nr', 0, 'Domestic Electrical', TRUE),
  ('MAT-0247', 'Switches', 'nr', 0, 'Domestic Electrical', TRUE),
  ('MAT-0248', 'Downlights', 'nr', 0, 'Domestic Electrical', TRUE),
  ('MAT-0249', 'Smoke detectors', 'nr', 0, 'Domestic Electrical', TRUE),
  ('MAT-0250', 'Back boxes', 'nr', 0, 'Domestic Electrical', TRUE),
  ('MAT-0251', 'Conduit', 'nr', 0, 'Domestic Electrical', TRUE),
  ('MAT-0252', 'FP cable', 'nr', 0, 'Commercial Electrical', TRUE),
  ('MAT-0253', 'Tray', 'nr', 0, 'Commercial Electrical', TRUE),
  ('MAT-0254', 'Basket', 'nr', 0, 'Commercial Electrical', TRUE),
  ('MAT-0255', 'Trunking', 'nr', 0, 'Commercial Electrical', TRUE),
  ('MAT-0256', 'Containment', 'nr', 0, 'Commercial Electrical', TRUE),
  ('MAT-0257', 'Distribution board', 'nr', 0, 'Commercial Electrical', TRUE),
  ('MAT-0258', 'Isolators', 'nr', 0, 'Commercial Electrical', TRUE),
  ('MAT-0259', 'Emergency lighting', 'nr', 0, 'Commercial Electrical', TRUE),
  ('MAT-0260', 'Data points', 'nr', 0, 'Commercial Electrical', TRUE),
  ('MAT-0261', 'Armoured cable', 'nr', 0, 'Industrial Electrical', TRUE),
  ('MAT-0262', 'Steel conduit', 'nr', 0, 'Industrial Electrical', TRUE),
  ('MAT-0263', 'Cable ladder', 'nr', 0, 'Industrial Electrical', TRUE),
  ('MAT-0264', 'Gland kits', 'nr', 0, 'Industrial Electrical', TRUE),
  ('MAT-0265', 'MCC panels', 'nr', 0, 'Industrial Electrical', TRUE),
  ('MAT-0266', 'Control cabling', 'nr', 0, 'Industrial Electrical', TRUE),
  ('MAT-0267', 'Industrial isolators', 'nr', 0, 'Industrial Electrical', TRUE),
  ('MAT-0268', 'Containment systems', 'nr', 0, 'Industrial Electrical', TRUE),
  ('MAT-0269', 'EV charger unit', 'nr', 0, 'EV Chargers', TRUE),
  ('MAT-0270', 'Isolator', 'nr', 0, 'EV Chargers', TRUE),
  ('MAT-0271', 'Concrete base', 'nr', 0, 'EV Chargers', TRUE),
  ('MAT-0272', 'Earth rod', 'nr', 0, 'EV Chargers', TRUE),
  ('MAT-0273', 'Signage', 'nr', 0, 'EV Chargers', TRUE),
  ('MAT-0274', 'Foundations', 'nr', 0, 'Street Electrical / Feeder Pillars', TRUE),
  ('MAT-0275', 'Columns', 'nr', 0, 'Street Electrical / Feeder Pillars', TRUE),
  ('MAT-0276', 'Transformer', 'nr', 0, 'Substations', TRUE),
  ('MAT-0277', 'Switchgear', 'nr', 0, 'Substations', TRUE),
  ('MAT-0278', 'GRP kiosk', 'nr', 0, 'Substations', TRUE),
  ('MAT-0279', 'Earthing tape', 'nr', 0, 'Substations', TRUE),
  ('MAT-0280', 'Earthing rods', 'nr', 0, 'Substations', TRUE),
  ('MAT-0281', 'HV cable', 'nr', 0, 'Substations', TRUE),
  ('MAT-0282', 'LV cable', 'nr', 0, 'Substations', TRUE),
  ('MAT-0283', 'Feeder pillars', 'nr', 0, 'Substations', TRUE),
  ('MAT-0284', 'Plinths', 'nr', 0, 'Substations', TRUE),
  ('MAT-0285', 'Copper tube', 'nr', 0, 'Domestic Plumbing', TRUE),
  ('MAT-0286', 'PEX pipe', 'nr', 0, 'Domestic Plumbing', TRUE),
  ('MAT-0287', 'Waste pipe', 'nr', 0, 'Domestic Plumbing', TRUE),
  ('MAT-0288', 'Taps', 'nr', 0, 'Domestic Plumbing', TRUE),
  ('MAT-0289', 'WC', 'nr', 0, 'Domestic Plumbing', TRUE),
  ('MAT-0290', 'Basin', 'nr', 0, 'Domestic Plumbing', TRUE),
  ('MAT-0291', 'Bath', 'nr', 0, 'Domestic Plumbing', TRUE),
  ('MAT-0292', 'Shower', 'nr', 0, 'Domestic Plumbing', TRUE),
  ('MAT-0293', 'Traps', 'nr', 0, 'Domestic Plumbing', TRUE),
  ('MAT-0294', 'Copper pipe', 'nr', 0, 'Commercial Plumbing / Public Health', TRUE),
  ('MAT-0295', 'Stainless pipe', 'nr', 0, 'Commercial Plumbing / Public Health', TRUE),
  ('MAT-0296', 'HDPE pipe', 'nr', 0, 'Commercial Plumbing / Public Health', TRUE),
  ('MAT-0297', 'Rainwater pipe', 'nr', 0, 'Commercial Plumbing / Public Health', TRUE),
  ('MAT-0298', 'Expansion vessels', 'nr', 0, 'Commercial Plumbing / Public Health', TRUE),
  ('MAT-0299', 'Boosted water components', 'nr', 0, 'Commercial Plumbing / Public Health', TRUE),
  ('MAT-0300', 'Sanitaryware', 'nr', 0, 'Commercial Plumbing / Public Health', TRUE),
  ('MAT-0301', 'Drainage pipework', 'nr', 0, 'Commercial Plumbing / Public Health', TRUE),
  ('MAT-0302', 'Ductwork', 'nr', 0, 'Mechanical / HVAC', TRUE),
  ('MAT-0303', 'Grilles', 'nr', 0, 'Mechanical / HVAC', TRUE),
  ('MAT-0304', 'Diffusers', 'nr', 0, 'Mechanical / HVAC', TRUE),
  ('MAT-0305', 'Spiral duct', 'nr', 0, 'Mechanical / HVAC', TRUE),
  ('MAT-0306', 'Chilled water pipe', 'nr', 0, 'Mechanical / HVAC', TRUE),
  ('MAT-0307', 'FCUs', 'nr', 0, 'Mechanical / HVAC', TRUE),
  ('MAT-0308', 'AHUs', 'nr', 0, 'Mechanical / HVAC', TRUE),
  ('MAT-0309', 'Extract fans', 'nr', 0, 'Mechanical / HVAC', TRUE),
  ('MAT-0310', 'Supports', 'nr', 0, 'Mechanical / HVAC', TRUE),
  ('MAT-0311', 'Boiler', 'nr', 0, 'Domestic Heating', TRUE),
  ('MAT-0312', 'Radiator', 'nr', 0, 'Domestic Heating', TRUE),
  ('MAT-0313', 'TRV', 'nr', 0, 'Domestic Heating', TRUE),
  ('MAT-0314', 'Controls', 'nr', 0, 'Domestic Heating', TRUE),
  ('MAT-0315', 'Cylinder', 'nr', 0, 'Domestic Heating', TRUE),
  ('MAT-0316', 'Flue kit', 'nr', 0, 'Domestic Heating', TRUE),
  ('MAT-0317', 'Magnetic filter', 'nr', 0, 'Domestic Heating', TRUE),
  ('MAT-0318', 'Split AC unit', 'nr', 0, 'Air Conditioning / Refrigeration', TRUE),
  ('MAT-0319', 'Condensers', 'nr', 0, 'Air Conditioning / Refrigeration', TRUE),
  ('MAT-0320', 'Pipe insulation', 'nr', 0, 'Air Conditioning / Refrigeration', TRUE),
  ('MAT-0321', 'Copper line set', 'nr', 0, 'Air Conditioning / Refrigeration', TRUE),
  ('MAT-0322', 'Condensate pump', 'nr', 0, 'Air Conditioning / Refrigeration', TRUE),
  ('MAT-0323', 'Control cable', 'nr', 0, 'Air Conditioning / Refrigeration', TRUE),
  ('MAT-0324', 'Fire alarm cable', 'nr', 0, 'Fire Alarm & Life Safety', TRUE),
  ('MAT-0325', 'Smoke detector', 'nr', 0, 'Fire Alarm & Life Safety', TRUE),
  ('MAT-0326', 'Heat detector', 'nr', 0, 'Fire Alarm & Life Safety', TRUE),
  ('MAT-0327', 'Sounder', 'nr', 0, 'Fire Alarm & Life Safety', TRUE),
  ('MAT-0328', 'Call point', 'nr', 0, 'Fire Alarm & Life Safety', TRUE),
  ('MAT-0329', 'Control panel', 'nr', 0, 'Fire Alarm & Life Safety', TRUE),
  ('MAT-0330', 'Interface unit', 'nr', 0, 'Fire Alarm & Life Safety', TRUE),
  ('MAT-0331', 'CCTV camera', 'nr', 0, 'Security / CCTV / Access Control', TRUE),
  ('MAT-0332', 'NVR', 'nr', 0, 'Security / CCTV / Access Control', TRUE),
  ('MAT-0333', 'Access control panel', 'nr', 0, 'Security / CCTV / Access Control', TRUE),
  ('MAT-0334', 'Mag lock', 'nr', 0, 'Security / CCTV / Access Control', TRUE),
  ('MAT-0335', 'Reader', 'nr', 0, 'Security / CCTV / Access Control', TRUE),
  ('MAT-0336', 'Data cable', 'nr', 0, 'Security / CCTV / Access Control', TRUE),
  ('MAT-0337', 'Power supply', 'nr', 0, 'Security / CCTV / Access Control', TRUE),
  ('MAT-0338', 'Boards', 'nr', 0, 'Drylining & Partitions', TRUE),
  ('MAT-0339', 'Studs', 'nr', 0, 'Drylining & Partitions', TRUE),
  ('MAT-0340', 'Tracks', 'nr', 0, 'Drylining & Partitions', TRUE),
  ('MAT-0341', 'Screws', 'nr', 0, 'Drylining & Partitions', TRUE),
  ('MAT-0342', 'Joint tape', 'nr', 0, 'Drylining & Partitions', TRUE),
  ('MAT-0343', 'Access panels', 'nr', 0, 'Drylining & Partitions', TRUE),
  ('MAT-0344', 'Skim plaster', 'nr', 0, 'Plastering & Rendering', TRUE),
  ('MAT-0345', 'Bonding plaster', 'nr', 0, 'Plastering & Rendering', TRUE),
  ('MAT-0346', 'Render system', 'nr', 0, 'Plastering & Rendering', TRUE),
  ('MAT-0347', 'Beads', 'nr', 0, 'Plastering & Rendering', TRUE),
  ('MAT-0348', 'Additives', 'nr', 0, 'Plastering & Rendering', TRUE),
  ('MAT-0349', 'Skirting', 'nr', 0, 'Carpentry & Joinery', TRUE),
  ('MAT-0350', 'Architrave', 'nr', 0, 'Carpentry & Joinery', TRUE),
  ('MAT-0351', 'Ironmongery', 'nr', 0, 'Carpentry & Joinery', TRUE),
  ('MAT-0352', 'MDF', 'nr', 0, 'Carpentry & Joinery', TRUE),
  ('MAT-0353', 'Plywood', 'nr', 0, 'Carpentry & Joinery', TRUE),
  ('MAT-0354', 'Trims', 'nr', 0, 'Carpentry & Joinery', TRUE),
  ('MAT-0355', 'Cabinets', 'nr', 0, 'Kitchen Installation', TRUE),
  ('MAT-0356', 'Worktops', 'nr', 0, 'Kitchen Installation', TRUE),
  ('MAT-0357', 'Sinks', 'nr', 0, 'Kitchen Installation', TRUE),
  ('MAT-0358', 'Splashbacks', 'nr', 0, 'Kitchen Installation', TRUE),
  ('MAT-0359', 'Appliances', 'nr', 0, 'Kitchen Installation', TRUE),
  ('MAT-0360', 'Handles', 'nr', 0, 'Kitchen Installation', TRUE),
  ('MAT-0361', 'Shower tray', 'nr', 0, 'Bathroom Installation', TRUE),
  ('MAT-0362', 'Shower screen', 'nr', 0, 'Bathroom Installation', TRUE),
  ('MAT-0363', 'Vanity unit', 'nr', 0, 'Bathroom Installation', TRUE),
  ('MAT-0364', 'Tiles', 'nr', 0, 'Bathroom Installation', TRUE),
  ('MAT-0365', 'Adhesive', 'nr', 0, 'Bathroom Installation', TRUE),
  ('MAT-0366', 'Grout', 'nr', 0, 'Bathroom Installation', TRUE),
  ('MAT-0367', 'Ceramic tiles', 'nr', 0, 'Tiling', TRUE),
  ('MAT-0368', 'Porcelain tiles', 'nr', 0, 'Tiling', TRUE),
  ('MAT-0369', 'Natural stone tiles', 'nr', 0, 'Tiling', TRUE),
  ('MAT-0370', 'Trim', 'nr', 0, 'Tiling', TRUE),
  ('MAT-0371', 'Primers', 'nr', 0, 'Tiling', TRUE),
  ('MAT-0372', 'Levelling clips', 'nr', 0, 'Tiling', TRUE),
  ('MAT-0373', 'Carpet tile', 'nr', 0, 'Flooring', TRUE),
  ('MAT-0374', 'Sheet vinyl', 'nr', 0, 'Flooring', TRUE),
  ('MAT-0375', 'LVT', 'nr', 0, 'Flooring', TRUE),
  ('MAT-0376', 'Laminate', 'nr', 0, 'Flooring', TRUE),
  ('MAT-0377', 'Engineered timber', 'nr', 0, 'Flooring', TRUE),
  ('MAT-0378', 'Underlay', 'nr', 0, 'Flooring', TRUE),
  ('MAT-0379', 'Leveller', 'nr', 0, 'Flooring', TRUE),
  ('MAT-0380', 'DPM membrane', 'nr', 0, 'Flooring', TRUE),
  ('MAT-0381', 'MF ceiling system', 'nr', 0, 'Ceilings', TRUE),
  ('MAT-0382', 'Grid system', 'nr', 0, 'Ceilings', TRUE),
  ('MAT-0383', 'Ceiling tiles', 'nr', 0, 'Ceilings', TRUE),
  ('MAT-0384', 'Hangers', 'nr', 0, 'Ceilings', TRUE),
  ('MAT-0385', 'Perimeter trim', 'nr', 0, 'Ceilings', TRUE),
  ('MAT-0386', 'Access hatches', 'nr', 0, 'Ceilings', TRUE),
  ('MAT-0387', 'Emulsion', 'nr', 0, 'Painting & Decorating', TRUE),
  ('MAT-0388', 'Eggshell', 'nr', 0, 'Painting & Decorating', TRUE),
  ('MAT-0389', 'Gloss', 'nr', 0, 'Painting & Decorating', TRUE),
  ('MAT-0390', 'Filler', 'nr', 0, 'Painting & Decorating', TRUE),
  ('MAT-0391', 'Caulk', 'nr', 0, 'Painting & Decorating', TRUE),
  ('MAT-0392', 'Wallpaper', 'nr', 0, 'Painting & Decorating', TRUE),
  ('MAT-0393', 'Masking tape', 'nr', 0, 'Painting & Decorating', TRUE),
  ('MAT-0394', 'Fire mastic', 'nr', 0, 'Fire Stopping', TRUE),
  ('MAT-0395', 'Fire batt', 'nr', 0, 'Fire Stopping', TRUE),
  ('MAT-0396', 'Fire collars', 'nr', 0, 'Fire Stopping', TRUE),
  ('MAT-0397', 'Wraps', 'nr', 0, 'Fire Stopping', TRUE),
  ('MAT-0398', 'Acoustic sealant', 'nr', 0, 'Fire Stopping', TRUE),
  ('MAT-0399', 'Fire foam', 'nr', 0, 'Fire Stopping', TRUE),
  ('MAT-0400', 'Top coat', 'nr', 0, 'Passive Fire Protection / Intumescent', TRUE),
  ('MAT-0401', 'Diamond core bits', 'nr', 0, 'Diamond Drilling & Sawing', TRUE),
  ('MAT-0402', 'Blades', 'nr', 0, 'Diamond Drilling & Sawing', TRUE),
  ('MAT-0403', 'Anchor fixings', 'nr', 0, 'Diamond Drilling & Sawing', TRUE),
  ('MAT-0404', 'Water feed consumables', 'nr', 0, 'Diamond Drilling & Sawing', TRUE),
  ('MAT-0405', 'Sand/cement', 'nr', 0, 'Builderswork in Connection', TRUE),
  ('MAT-0406', 'Mortar', 'nr', 0, 'Builderswork in Connection', TRUE),
  ('MAT-0407', 'Ply', 'nr', 0, 'Builderswork in Connection', TRUE),
  ('MAT-0408', 'Making-good materials', 'nr', 0, 'Builderswork in Connection', TRUE),
  ('MAT-0409', 'Resin', 'nr', 0, 'Specialist Finishes', TRUE),
  ('MAT-0410', 'Hardener', 'nr', 0, 'Specialist Finishes', TRUE),
  ('MAT-0411', 'Quartz aggregate', 'nr', 0, 'Specialist Finishes', TRUE),
  ('MAT-0412', 'Microcement', 'nr', 0, 'Specialist Finishes', TRUE),
  ('MAT-0413', 'Decorative plaster', 'nr', 0, 'Specialist Finishes', TRUE),
  ('MAT-0414', 'Sealers', 'nr', 0, 'Specialist Finishes', TRUE),
  ('MAT-0415', 'Waste segregation bins', 'nr', 0, 'Waste Management / Logistics', TRUE),
  ('MAT-0416', 'Protection sheeting', 'nr', 0, 'Waste Management / Logistics', TRUE),
  ('MAT-0417', 'Labels and signage', 'nr', 0, 'Waste Management / Logistics', TRUE) ON CONFLICT DO NOTHING;

-- Done: 60 trades, ~1038 items total