ALTER TABLE project_expenses
ADD COLUMN IF NOT EXISTS quantity NUMERIC(12,2) DEFAULT 1,
ADD COLUMN IF NOT EXISTS unit_rate NUMERIC(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS unit TEXT DEFAULT 'item',
ADD COLUMN IF NOT EXISTS delivery_cost NUMERIC(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS surcharge_cost NUMERIC(12,2) DEFAULT 0; -- e.g. Part Load
