-- Sprint 9b: Import comprehensive trade library from ChatGPT dataset
-- Generated automatically from 21 trades, 650 items

-- LABOUR RATES
INSERT INTO labour_rates (trade, role, day_rate, region, is_system_default) VALUES
  ('Groundworks & Civils', 'Groundworker', 260, 'national', TRUE),
  ('Groundworks & Civils', 'General Operative', 180, 'national', TRUE),
  ('Groundworks & Civils', 'Plant Operator', 290, 'national', TRUE),
  ('Groundworks & Civils', 'Excavator Operator', 300, 'national', TRUE),
  ('Groundworks & Civils', 'Groundworks Supervisor', 340, 'national', TRUE),
  ('Groundworks & Civils', 'Setting Out Engineer', 360, 'national', TRUE),
  ('Drainage & Utilities', 'Drainage Operative', 265, 'national', TRUE),
  ('Drainage & Utilities', 'Groundworker', 260, 'national', TRUE),
  ('Drainage & Utilities', 'Pipe Layer', 285, 'national', TRUE),
  ('Drainage & Utilities', 'Plant Operator', 290, 'national', TRUE),
  ('Drainage & Utilities', 'Confined Space Operative', 310, 'national', TRUE),
  ('Drainage & Utilities', 'Drainage Supervisor', 350, 'national', TRUE),
  ('Concrete Works', 'Concrete Finisher', 285, 'national', TRUE),
  ('Concrete Works', 'Shuttering Carpenter', 300, 'national', TRUE),
  ('Concrete Works', 'Steel Fixer', 300, 'national', TRUE),
  ('Concrete Works', 'General Operative', 180, 'national', TRUE),
  ('Concrete Works', 'Pump Operative', 320, 'national', TRUE),
  ('Concrete Works', 'Concrete Supervisor', 350, 'national', TRUE),
  ('Surfacing & Paving', 'Paver', 255, 'national', TRUE),
  ('Surfacing & Paving', 'Groundworker', 260, 'national', TRUE),
  ('Surfacing & Paving', 'Asphalt Operative', 275, 'national', TRUE),
  ('Surfacing & Paving', 'Roller Driver', 285, 'national', TRUE),
  ('Surfacing & Paving', 'General Operative', 180, 'national', TRUE),
  ('Surfacing & Paving', 'Surfacing Supervisor', 340, 'national', TRUE),
  ('Masonry & Brickwork', 'Bricklayer', 275, 'national', TRUE),
  ('Masonry & Brickwork', 'Block Layer', 270, 'national', TRUE),
  ('Masonry & Brickwork', 'Labourer', 180, 'national', TRUE),
  ('Masonry & Brickwork', 'Mason', 295, 'national', TRUE),
  ('Masonry & Brickwork', 'Brickwork Foreman', 340, 'national', TRUE),
  ('Masonry & Brickwork', 'Tuck Pointer', 290, 'national', TRUE),
  ('Carpentry & Joinery', 'Carpenter', 275, 'national', TRUE),
  ('Carpentry & Joinery', 'Joiner', 285, 'national', TRUE),
  ('Carpentry & Joinery', 'Shopfitter Carpenter', 295, 'national', TRUE),
  ('Carpentry & Joinery', 'Labourer', 180, 'national', TRUE),
  ('Carpentry & Joinery', 'Carpentry Foreman', 345, 'national', TRUE),
  ('Carpentry & Joinery', 'Bench Joiner', 290, 'national', TRUE),
  ('Electrical', 'Electrician', 325, 'national', TRUE),
  ('Electrical', 'Electrical Improver', 230, 'national', TRUE),
  ('Electrical', 'Approved Electrician', 350, 'national', TRUE),
  ('Electrical', 'Electrical Mate', 185, 'national', TRUE),
  ('Electrical', 'Test Engineer', 360, 'national', TRUE),
  ('Electrical', 'Electrical Supervisor', 395, 'national', TRUE),
  ('Plumbing & Mechanical', 'Plumber', 330, 'national', TRUE),
  ('Plumbing & Mechanical', 'Pipefitter', 340, 'national', TRUE),
  ('Plumbing & Mechanical', 'Gas Safe Engineer', 360, 'national', TRUE),
  ('Plumbing & Mechanical', 'Heating Engineer', 350, 'national', TRUE),
  ('Plumbing & Mechanical', 'Plumber''s Mate', 185, 'national', TRUE),
  ('Plumbing & Mechanical', 'Mechanical Supervisor', 395, 'national', TRUE),
  ('Plastering & Drylining', 'Plasterer', 300, 'national', TRUE),
  ('Plastering & Drylining', 'Dryliner', 285, 'national', TRUE),
  ('Plastering & Drylining', 'Ceiling Fixer', 285, 'national', TRUE),
  ('Plastering & Drylining', 'Labourer', 180, 'national', TRUE),
  ('Plastering & Drylining', 'Tape and Jointer', 270, 'national', TRUE),
  ('Plastering & Drylining', 'Drylining Supervisor', 340, 'national', TRUE),
  ('Painting & Decorating', 'Painter and Decorator', 245, 'national', TRUE),
  ('Painting & Decorating', 'Spray Painter', 270, 'national', TRUE),
  ('Painting & Decorating', 'Paperhanger', 255, 'national', TRUE),
  ('Painting & Decorating', 'Labourer', 180, 'national', TRUE),
  ('Painting & Decorating', 'Decorator Foreman', 320, 'national', TRUE),
  ('Roofing', 'Roofer', 285, 'national', TRUE),
  ('Roofing', 'Slater', 295, 'national', TRUE),
  ('Roofing', 'Tiler Roofer', 290, 'national', TRUE),
  ('Roofing', 'Leadworker', 320, 'national', TRUE),
  ('Roofing', 'Roofing Labourer', 185, 'national', TRUE),
  ('Roofing', 'Roofing Supervisor', 345, 'national', TRUE),
  ('Landscaping & External Works', 'Landscaper', 240, 'national', TRUE),
  ('Landscaping & External Works', 'Soft Landscaper', 230, 'national', TRUE),
  ('Landscaping & External Works', 'Fencer', 245, 'national', TRUE),
  ('Landscaping & External Works', 'Groundworker', 260, 'national', TRUE),
  ('Landscaping & External Works', 'General Operative', 180, 'national', TRUE),
  ('Landscaping & External Works', 'Landscaping Supervisor', 320, 'national', TRUE),
  ('Steel & Structural', 'Steel Erector', 320, 'national', TRUE),
  ('Steel & Structural', 'Fabricator', 310, 'national', TRUE),
  ('Steel & Structural', 'Welder', 320, 'national', TRUE),
  ('Steel & Structural', 'Banksman', 220, 'national', TRUE),
  ('Steel & Structural', 'Slinger Signaller', 290, 'national', TRUE),
  ('Steel & Structural', 'Structural Supervisor', 395, 'national', TRUE),
  ('Demolition & Strip Out', 'Demolition Operative', 240, 'national', TRUE),
  ('Demolition & Strip Out', 'Strip Out Operative', 230, 'national', TRUE),
  ('Demolition & Strip Out', 'Plant Operator', 290, 'national', TRUE),
  ('Demolition & Strip Out', 'Burner', 310, 'national', TRUE),
  ('Demolition & Strip Out', 'Demolition Supervisor', 360, 'national', TRUE),
  ('Demolition & Strip Out', 'Labourer', 180, 'national', TRUE),
  ('Fit-Out & Finishes', 'General Builder', 260, 'national', TRUE),
  ('Fit-Out & Finishes', 'Fit-Out Carpenter', 295, 'national', TRUE),
  ('Fit-Out & Finishes', 'Partition Fixer', 285, 'national', TRUE),
  ('Fit-Out & Finishes', 'Ceiling Fixer', 285, 'national', TRUE),
  ('Fit-Out & Finishes', 'Labourer', 180, 'national', TRUE),
  ('Fit-Out & Finishes', 'Fit-Out Supervisor', 360, 'national', TRUE),
  ('Tiling & Flooring', 'Wall and Floor Tiler', 270, 'national', TRUE),
  ('Tiling & Flooring', 'Floor Layer', 275, 'national', TRUE),
  ('Tiling & Flooring', 'Vinyl Installer', 280, 'national', TRUE),
  ('Tiling & Flooring', 'Carpet Fitter', 250, 'national', TRUE),
  ('Tiling & Flooring', 'Labourer', 180, 'national', TRUE),
  ('Tiling & Flooring', 'Flooring Supervisor', 330, 'national', TRUE),
  ('Glazing & Windows/Doors', 'Window Fitter', 285, 'national', TRUE),
  ('Glazing & Windows/Doors', 'Glazier', 295, 'national', TRUE),
  ('Glazing & Windows/Doors', 'Door Installer', 285, 'national', TRUE),
  ('Glazing & Windows/Doors', 'Glazing Labourer', 185, 'national', TRUE),
  ('Glazing & Windows/Doors', 'Curtain Wall Installer', 320, 'national', TRUE),
  ('Glazing & Windows/Doors', 'Glazing Supervisor', 350, 'national', TRUE),
  ('Insulation & Damp Proofing', 'Insulation Installer', 240, 'national', TRUE),
  ('Insulation & Damp Proofing', 'Damp Proofing Operative', 255, 'national', TRUE),
  ('Insulation & Damp Proofing', 'Cavity Wall Installer', 245, 'national', TRUE),
  ('Insulation & Damp Proofing', 'General Operative', 180, 'national', TRUE),
  ('Insulation & Damp Proofing', 'Damp Proofing Supervisor', 320, 'national', TRUE),
  ('Kitchen & Bathroom Installation', 'Kitchen Fitter', 275, 'national', TRUE),
  ('Kitchen & Bathroom Installation', 'Bathroom Fitter', 285, 'national', TRUE),
  ('Kitchen & Bathroom Installation', 'Carpenter', 275, 'national', TRUE),
  ('Kitchen & Bathroom Installation', 'Plumber', 330, 'national', TRUE),
  ('Kitchen & Bathroom Installation', 'Electrician', 325, 'national', TRUE),
  ('Kitchen & Bathroom Installation', 'Labourer', 180, 'national', TRUE),
  ('Scaffolding & Access', 'Scaffolder', 290, 'national', TRUE),
  ('Scaffolding & Access', 'Advanced Scaffolder', 320, 'national', TRUE),
  ('Scaffolding & Access', 'Scaffold Labourer', 185, 'national', TRUE),
  ('Scaffolding & Access', 'Scaffold Inspector', 330, 'national', TRUE),
  ('Scaffolding & Access', 'Scaffold Supervisor', 350, 'national', TRUE),
  ('Waste Management & Site Setup', 'Site Labourer', 180, 'national', TRUE),
  ('Waste Management & Site Setup', 'Traffic Marshal', 210, 'national', TRUE),
  ('Waste Management & Site Setup', 'Gateperson', 190, 'national', TRUE),
  ('Waste Management & Site Setup', 'Site Manager', 390, 'national', TRUE),
  ('Waste Management & Site Setup', 'Storeman', 215, 'national', TRUE) ON CONFLICT DO NOTHING;

-- PLANT RATES (as cost library items, category=Plant)
-- First clear existing plant entries to avoid duplication
DELETE FROM cost_library_items WHERE category = 'Plant' AND is_system_default = TRUE AND id NOT IN (SELECT cost_library_item_id FROM estimate_lines WHERE cost_library_item_id IS NOT NULL);
INSERT INTO cost_library_items (code, description, unit, base_rate, category, is_system_default) VALUES
  ('PL-15TEXC', '1.5t excavator', 'day', 120, 'Plant', TRUE),
  ('PL-3TEXCA', '3t excavator', 'day', 165, 'Plant', TRUE),
  ('PL-5TEXCA', '5t excavator', 'day', 220, 'Plant', TRUE),
  ('PL-8TEXCA', '8t excavator', 'day', 295, 'Plant', TRUE),
  ('PL-9TDUMP', '9t dumper', 'day', 185, 'Plant', TRUE),
  ('PL-RIDEON', 'Ride-on roller', 'day', 125, 'Plant', TRUE),
  ('PL-PLATEC', 'Plate compactor', 'day', 32, 'Plant', TRUE),
  ('PL-TRENCH', 'Trench rammer', 'day', 38, 'Plant', TRUE),
  ('PL-LASERL', 'Laser level', 'day', 28, 'Plant', TRUE),
  ('PL-CONCRE', 'Concrete breaker', 'day', 45, 'Plant', TRUE),
  ('PL-DUMPER', 'Dumper 6t', 'day', 145, 'Plant', TRUE),
  ('PL-TRENCH2', 'Trench box', 'day', 95, 'Plant', TRUE),
  ('PL-PIPELA', 'Pipe laser', 'day', 48, 'Plant', TRUE),
  ('PL-PETROL', 'Petrol water pump', 'day', 36, 'Plant', TRUE),
  ('PL-PIPECU', 'Pipe cutter', 'day', 18, 'Plant', TRUE),
  ('PL-CABLEA', 'Cable avoidance tool', 'day', 28, 'Plant', TRUE),
  ('PL-MANHOL', 'Manhole lifting keys', 'day', 8, 'Plant', TRUE),
  ('PL-JETTIN', 'Jetting unit', 'day', 140, 'Plant', TRUE),
  ('PL-CONCRE2', 'Concrete poker', 'day', 28, 'Plant', TRUE),
  ('PL-POWERF', 'Power float', 'day', 68, 'Plant', TRUE),
  ('PL-CONCRE3', 'Concrete mixer', 'day', 42, 'Plant', TRUE),
  ('PL-FLOORS', 'Floor saw', 'day', 62, 'Plant', TRUE),
  ('PL-BEAMSC', 'Beam screed', 'day', 55, 'Plant', TRUE),
  ('PL-POWERT', 'Power trowel', 'day', 72, 'Plant', TRUE),
  ('PL-CONCRE4', 'Concrete skip', 'day', 35, 'Plant', TRUE),
  ('PL-MINICR', 'Mini crane', 'day', 210, 'Plant', TRUE),
  ('PL-FORMWO', 'Formwork props', 'day', 2.5, 'Plant', TRUE),
  ('PL-FORWAR', 'Forward roller', 'day', 85, 'Plant', TRUE),
  ('PL-CUTOFF', 'Cut-off saw', 'day', 42, 'Plant', TRUE),
  ('PL-ROADSA', 'Road saw', 'day', 68, 'Plant', TRUE),
  ('PL-HOTBOX', 'Hot box', 'day', 95, 'Plant', TRUE),
  ('PL-POWERB', 'Power barrow', 'day', 55, 'Plant', TRUE),
  ('PL-BLOCKS', 'Block splitter', 'day', 24, 'Plant', TRUE),
  ('PL-TARBOI', 'Tar boiler', 'day', 48, 'Plant', TRUE),
  ('PL-LINEMA', 'Line marker', 'day', 35, 'Plant', TRUE),
  ('PL-BRICKS', 'Brick saw', 'day', 42, 'Plant', TRUE),
  ('PL-MORTAR', 'Mortar mixer', 'day', 42, 'Plant', TRUE),
  ('PL-HOPUPP', 'Hop-up platform', 'day', 14, 'Plant', TRUE),
  ('PL-BRICKE', 'Brick elevator', 'day', 65, 'Plant', TRUE),
  ('PL-MIXERS', 'Mixer stand', 'day', 8, 'Plant', TRUE),
  ('PL-DUSTEX', 'Dust extractor', 'day', 22, 'Plant', TRUE),
  ('PL-110VAN', '110v angle grinder', 'day', 18, 'Plant', TRUE),
  ('PL-BLOCKC', 'Block cart', 'day', 12, 'Plant', TRUE),
  ('PL-MITRES', 'Mitre saw', 'day', 28, 'Plant', TRUE),
  ('PL-TABLES', 'Table saw', 'day', 42, 'Plant', TRUE),
  ('PL-NAILGU', 'Nail gun', 'day', 18, 'Plant', TRUE),
  ('PL-ROUTER', 'Router', 'day', 22, 'Plant', TRUE),
  ('PL-PLANER', 'Planer', 'day', 20, 'Plant', TRUE),
  ('PL-SDSDRI', 'SDS drill', 'day', 16, 'Plant', TRUE),
  ('PL-WORKPL', 'Work platform', 'day', 12, 'Plant', TRUE),
  ('PL-PASLOD', 'Paslode fixings gun', 'day', 20, 'Plant', TRUE),
  ('PL-CABLED', 'Cable drum jack', 'day', 18, 'Plant', TRUE),
  ('PL-CABLEP', 'Cable puller', 'day', 42, 'Plant', TRUE),
  ('PL-COREDR', 'Core drill', 'day', 38, 'Plant', TRUE),
  ('PL-MEWPSC', 'MEWP scissor lift', 'day', 95, 'Plant', TRUE),
  ('PL-STEPLA', 'Step ladder set', 'day', 10, 'Plant', TRUE),
  ('PL-CIRCUI', 'Circuit tester', 'day', 20, 'Plant', TRUE),
  ('PL-CABLED2', 'Cable detector', 'day', 22, 'Plant', TRUE),
  ('PL-GENERA', 'Generator 6kVA', 'day', 45, 'Plant', TRUE),
  ('PL-PIPETH', 'Pipe threader', 'day', 32, 'Plant', TRUE),
  ('PL-PRESSF', 'Press-fit tool', 'day', 38, 'Plant', TRUE),
  ('PL-PIPEFR', 'Pipe freezing kit', 'day', 26, 'Plant', TRUE),
  ('PL-PIPEBE', 'Pipe bender', 'day', 22, 'Plant', TRUE),
  ('PL-DRAINA', 'Drain auger', 'day', 28, 'Plant', TRUE),
  ('PL-PRESSU', 'Pressure test pump', 'day', 18, 'Plant', TRUE),
  ('PL-SOLDER', 'Soldering kit', 'day', 12, 'Plant', TRUE),
  ('PL-BOARDL', 'Board lifter', 'day', 22, 'Plant', TRUE),
  ('PL-MIXERD', 'Mixer drill', 'day', 18, 'Plant', TRUE),
  ('PL-SCREWG', 'Screw gun', 'day', 16, 'Plant', TRUE),
  ('PL-PLASTE', 'Plaster spray machine', 'day', 110, 'Plant', TRUE),
  ('PL-DRYWAL', 'Drywall sander', 'day', 28, 'Plant', TRUE),
  ('PL-AIRLES', 'Airless paint sprayer', 'day', 58, 'Plant', TRUE),
  ('PL-TOWERS', 'Tower scaffold', 'day', 35, 'Plant', TRUE),
  ('PL-MEWPCH', 'MEWP cherry picker', 'day', 145, 'Plant', TRUE),
  ('PL-WALLPA', 'Wallpaper steamer', 'day', 18, 'Plant', TRUE),
  ('PL-DUSTLE', 'Dustless sander', 'day', 28, 'Plant', TRUE),
  ('PL-GENERA2', 'Generator 3kVA', 'day', 28, 'Plant', TRUE),
  ('PL-TILEHO', 'Tile hoist', 'day', 65, 'Plant', TRUE),
  ('PL-WELDER', 'Welder for single ply', 'day', 55, 'Plant', TRUE),
  ('PL-ROOFLA', 'Roof ladder', 'day', 12, 'Plant', TRUE),
  ('PL-DEBRIS', 'Debris chute', 'day', 25, 'Plant', TRUE),
  ('PL-MINIEX', 'Mini excavator 1.5t', 'day', 120, 'Plant', TRUE),
  ('PL-TRACKE', 'Tracked dumper', 'day', 135, 'Plant', TRUE),
  ('PL-TURFCU', 'Turf cutter', 'day', 48, 'Plant', TRUE),
  ('PL-POSTHO', 'Post hole auger', 'day', 42, 'Plant', TRUE),
  ('PL-CHAINS', 'Chainsaw', 'day', 28, 'Plant', TRUE),
  ('PL-HEDGET', 'Hedge trimmer', 'day', 18, 'Plant', TRUE),
  ('PL-ROTAVA', 'Rotavator', 'day', 42, 'Plant', TRUE),
  ('PL-SPIDER', 'Spider crane', 'day', 260, 'Plant', TRUE),
  ('PL-TELEHA', 'Telehandler 9m', 'day', 165, 'Plant', TRUE),
  ('PL-MEWPBO', 'MEWP boom lift', 'day', 145, 'Plant', TRUE),
  ('PL-MIGWEL', 'MIG welder', 'day', 38, 'Plant', TRUE),
  ('PL-MAGDRI', 'Mag drill', 'day', 22, 'Plant', TRUE),
  ('PL-TORQUE', 'Torque wrench', 'day', 12, 'Plant', TRUE),
  ('PL-CHAINB', 'Chain block', 'day', 14, 'Plant', TRUE),
  ('PL-BEAMTR', 'Beam trolley', 'day', 12, 'Plant', TRUE),
  ('PL-3TEXCA3', '3t excavator with breaker', 'day', 210, 'Plant', TRUE),
  ('PL-SKIDST', 'Skid steer loader', 'day', 145, 'Plant', TRUE),
  ('PL-BREAKE', 'Breaker 110v', 'day', 45, 'Plant', TRUE),
  ('PL-FLOORS2', 'Floor scraper', 'day', 58, 'Plant', TRUE),
  ('PL-DUSTSU', 'Dust suppression unit', 'day', 42, 'Plant', TRUE),
  ('PL-GRABLO', 'Grab lorry', 'day', 285, 'Plant', TRUE),
  ('PL-WASTEC', 'Waste chute', 'day', 25, 'Plant', TRUE),
  ('PL-AIRSCR', 'Air scrubber', 'day', 34, 'Plant', TRUE),
  ('PL-TILECU', 'Tile cutter', 'day', 18, 'Plant', TRUE),
  ('PL-WETTIL', 'Wet tile saw', 'day', 32, 'Plant', TRUE),
  ('PL-FLOORG', 'Floor grinder', 'day', 58, 'Plant', TRUE),
  ('PL-FLOORS4', 'Floor stripper', 'day', 62, 'Plant', TRUE),
  ('PL-CARPET', 'Carpet stretcher', 'day', 15, 'Plant', TRUE),
  ('PL-VINYLR', 'Vinyl roller', 'day', 10, 'Plant', TRUE),
  ('PL-KNEEKI', 'Knee kicker', 'day', 12, 'Plant', TRUE),
  ('PL-GLASSS', 'Glass sucker lifter', 'day', 42, 'Plant', TRUE),
  ('PL-SEALAN', 'Sealant gun battery', 'day', 12, 'Plant', TRUE),
  ('PL-INSULA', 'Insulation blower', 'day', 95, 'Plant', TRUE),
  ('PL-INJECT', 'Injection pump', 'day', 42, 'Plant', TRUE),
  ('PL-DEHUMI', 'Dehumidifier', 'day', 24, 'Plant', TRUE),
  ('PL-STAPLE', 'Staple gun', 'day', 8, 'Plant', TRUE),
  ('PL-THERMA', 'Thermal camera', 'day', 45, 'Plant', TRUE),
  ('PL-JIGSAW', 'Jigsaw', 'day', 15, 'Plant', TRUE),
  ('PL-WORKTO', 'Worktop jig', 'day', 18, 'Plant', TRUE),
  ('PL-LORRYL', 'Lorry loader crane', 'day', 285, 'Plant', TRUE),
  ('PL-MOBILE', 'Mobile access platform', 'day', 95, 'Plant', TRUE),
  ('PL-GINWHE', 'Gin wheel', 'day', 10, 'Plant', TRUE),
  ('PL-HARNES', 'Harness set', 'day', 8, 'Plant', TRUE),
  ('PL-DEBRIS2', 'Debris netting reel', 'day', 6, 'Plant', TRUE),
  ('PL-SKIP8Y', 'Skip 8 yard', 'week', 0, 'Plant', TRUE),
  ('PL-WELFAR', 'Welfare unit', 'day', 95, 'Plant', TRUE),
  ('PL-SITETO', 'Site toilet', 'day', 22, 'Plant', TRUE),
  ('PL-WATERB', 'Water bowser', 'day', 38, 'Plant', TRUE),
  ('PL-HERASF', 'Heras fence panel hire', 'day', 2.5, 'Plant', TRUE),
  ('PL-PEDEST', 'Pedestrian barrier', 'day', 1.8, 'Plant', TRUE) ON CONFLICT DO NOTHING;

-- MATERIALS (as cost library items)
-- Clear existing system default materials to avoid duplication
DELETE FROM cost_library_items WHERE is_system_default = TRUE AND category NOT IN ('Plant', 'Labour', 'Preliminaries', 'Subcontract', 'Consultancy', 'Provisional Sums') AND id NOT IN (SELECT cost_library_item_id FROM estimate_lines WHERE cost_library_item_id IS NOT NULL);
INSERT INTO cost_library_items (code, description, unit, base_rate, category, is_system_default) VALUES
  ('MAT-TYPE1M', 'Type 1 MOT sub-base', 'm³', 48, 'Groundworks & Civils', TRUE),
  ('MAT-6F2CAP', '6F2 capping', 'm³', 36, 'Groundworks & Civils', TRUE),
  ('MAT-SHARPS', 'Sharp sand', 'm³', 46, 'Groundworks & Civils', TRUE),
  ('MAT-BALLAS', 'Ballast', 'm³', 52, 'Groundworks & Civils', TRUE),
  ('MAT-TOPSOI', 'Topsoil', 'm³', 42, 'Groundworks & Civils', TRUE),
  ('MAT-GEOTEX', 'Geotextile membrane', 'm²', 1.8, 'Groundworks & Civils', TRUE),
  ('MAT-A142ME', 'A142 mesh', 'sheet', 32, 'Groundworks & Civils', TRUE),
  ('MAT-A193ME', 'A193 mesh', 'sheet', 39, 'Groundworks & Civils', TRUE),
  ('MAT-DPM120', 'DPM 1200 gauge', 'm²', 1.9, 'Groundworks & Civils', TRUE),
  ('MAT-CONCRE', 'Concrete spacers', 'each', 0.25, 'Groundworks & Civils', TRUE),
  ('MAT-TIMBER', 'Timber formwork boards', 'm', 3.5, 'Groundworks & Civils', TRUE),
  ('MAT-MARKER', 'Marker spray paint', 'can', 6.5, 'Groundworks & Civils', TRUE),
  ('MAT-110MMU', '110mm uPVC pipe', 'm', 5.8, 'Drainage & Utilities', TRUE),
  ('MAT-160MMU', '160mm uPVC pipe', 'm', 11.5, 'Drainage & Utilities', TRUE),
  ('MAT-225MMT', '225mm twinwall pipe', 'm', 24, 'Drainage & Utilities', TRUE),
  ('MAT-110MMB', '110mm bend', 'each', 7.5, 'Drainage & Utilities', TRUE),
  ('MAT-110MMJ', '110mm junction', 'each', 14, 'Drainage & Utilities', TRUE),
  ('MAT-BOTTLE', 'Bottle gully', 'each', 23, 'Drainage & Utilities', TRUE),
  ('MAT-INSPEC', 'Inspection chamber base', 'each', 42, 'Drainage & Utilities', TRUE),
  ('MAT-INSPEC2', 'Inspection chamber riser', 'each', 16, 'Drainage & Utilities', TRUE),
  ('MAT-INSPEC3', 'Inspection chamber cover and frame', 'each', 68, 'Drainage & Utilities', TRUE),
  ('MAT-CONCRE2', 'Concrete manhole rings', 'each', 42, 'Drainage & Utilities', TRUE),
  ('MAT-GRANUL', 'Granular pipe bedding', 'm³', 48, 'Drainage & Utilities', TRUE),
  ('MAT-WARNIN', 'Warning tape', 'roll', 7, 'Drainage & Utilities', TRUE),
  ('MAT-UTILIT', 'Utility ducting 100mm', 'm', 9.5, 'Drainage & Utilities', TRUE),
  ('MAT-DRAWRO', 'Draw rope', 'm', 0.35, 'Drainage & Utilities', TRUE),
  ('MAT-READYM', 'Ready-mix concrete C20/25', 'm³', 145, 'Concrete Works', TRUE),
  ('MAT-READYM2', 'Ready-mix concrete C25/30', 'm³', 152, 'Concrete Works', TRUE),
  ('MAT-READYM3', 'Ready-mix concrete C30/37', 'm³', 160, 'Concrete Works', TRUE),
  ('MAT-RCREIN', 'RC reinforcement bar T10', 'm', 1.4, 'Concrete Works', TRUE),
  ('MAT-RCREIN2', 'RC reinforcement bar T12', 'm', 1.95, 'Concrete Works', TRUE),
  ('MAT-RCREIN3', 'RC reinforcement bar T16', 'm', 3.1, 'Concrete Works', TRUE),
  ('MAT-A252ME', 'A252 mesh', 'sheet', 52, 'Concrete Works', TRUE),
  ('MAT-RELEAS', 'Release oil', 'litre', 3.8, 'Concrete Works', TRUE),
  ('MAT-FORMWO', 'Formwork plywood', 'sheet', 34, 'Concrete Works', TRUE),
  ('MAT-FORMWO2', 'Formwork timber 100 x 50', 'm', 2.9, 'Concrete Works', TRUE),
  ('MAT-CURING', 'Curing compound', 'litre', 4.2, 'Concrete Works', TRUE),
  ('MAT-EXPANS', 'Expansion joint filler', 'm', 3.4, 'Concrete Works', TRUE),
  ('MAT-WATERB', 'Waterbar', 'm', 8.5, 'Concrete Works', TRUE),
  ('MAT-ASPHAL', 'Asphalt base course', 'tonne', 92, 'Surfacing & Paving', TRUE),
  ('MAT-ASPHAL2', 'Asphalt wearing course', 'tonne', 118, 'Surfacing & Paving', TRUE),
  ('MAT-BITUME', 'Bitumen tack coat', 'litre', 2.2, 'Surfacing & Paving', TRUE),
  ('MAT-CONCRE3', 'Concrete block paving 50mm', 'm²', 18, 'Surfacing & Paving', TRUE),
  ('MAT-CONCRE4', 'Concrete block paving 60mm', 'm²', 22, 'Surfacing & Paving', TRUE),
  ('MAT-NATURA', 'Natural sandstone paving', 'm²', 32, 'Surfacing & Paving', TRUE),
  ('MAT-PORCEL', 'Porcelain paving', 'm²', 38, 'Surfacing & Paving', TRUE),
  ('MAT-EDGING', 'Edging kerb', 'm', 10.5, 'Surfacing & Paving', TRUE),
  ('MAT-KERBBE', 'Kerb bedding mortar', 'bag', 7.5, 'Surfacing & Paving', TRUE),
  ('MAT-JOINTI', 'Jointing sand', 'bag', 4.8, 'Surfacing & Paving', TRUE),
  ('MAT-PAVING', 'Paving primer', 'bag', 14.5, 'Surfacing & Paving', TRUE),
  ('MAT-RESINB', 'Resin-bound aggregate', 'm²', 27, 'Surfacing & Paving', TRUE),
  ('MAT-GEOGRI', 'Geogrid', 'm²', 3.2, 'Surfacing & Paving', TRUE),
  ('MAT-ROADMA', 'Road marking paint', 'litre', 8.5, 'Surfacing & Paving', TRUE),
  ('MAT-FACING', 'Facing brick', '1000', 780, 'Masonry & Brickwork', TRUE),
  ('MAT-ENGINE', 'Engineering brick Class A', '1000', 920, 'Masonry & Brickwork', TRUE),
  ('MAT-100MMC', '100mm concrete block', 'each', 1.9, 'Masonry & Brickwork', TRUE),
  ('MAT-140MMC', '140mm concrete block', 'each', 2.7, 'Masonry & Brickwork', TRUE),
  ('MAT-AIRCRE', 'Aircrete block 100mm', 'each', 2.8, 'Masonry & Brickwork', TRUE),
  ('MAT-CEMENT', 'Cement', 'bag', 7.2, 'Masonry & Brickwork', TRUE),
  ('MAT-HYDRAT', 'Hydrated lime', 'bag', 10.5, 'Masonry & Brickwork', TRUE),
  ('MAT-BUILDI', 'Building sand', 'm³', 52, 'Masonry & Brickwork', TRUE),
  ('MAT-MORTAR', 'Mortar plasticiser', 'litre', 2.8, 'Masonry & Brickwork', TRUE),
  ('MAT-WALLTI', 'Wall tie', 'each', 0.35, 'Masonry & Brickwork', TRUE),
  ('MAT-DPCROL', 'DPC roll 100mm', 'm', 0.95, 'Masonry & Brickwork', TRUE),
  ('MAT-CAVITY', 'Cavity tray', 'm', 6.5, 'Masonry & Brickwork', TRUE),
  ('MAT-LINTEL', 'Lintel', 'each', 65, 'Masonry & Brickwork', TRUE),
  ('MAT-WEEPVE', 'Weep vents', 'each', 1.2, 'Masonry & Brickwork', TRUE),
  ('MAT-MASONR', 'Masonry insulation batts', 'm²', 8.5, 'Masonry & Brickwork', TRUE),
  ('MAT-CLSTIM', 'CLS timber 38 x 89', 'm', 2.6, 'Carpentry & Joinery', TRUE),
  ('MAT-C24TRE', 'C24 treated timber 47 x 150', 'm', 5.8, 'Carpentry & Joinery', TRUE),
  ('MAT-PLYWOO', 'Plywood 18mm', 'sheet', 32, 'Carpentry & Joinery', TRUE),
  ('MAT-OSB318', 'OSB3 18mm', 'sheet', 22, 'Carpentry & Joinery', TRUE),
  ('MAT-MDF18M', 'MDF 18mm', 'sheet', 28, 'Carpentry & Joinery', TRUE),
  ('MAT-SKIRTI', 'Skirting board', 'm', 4.2, 'Carpentry & Joinery', TRUE),
  ('MAT-ARCHIT', 'Architrave', 'm', 3.6, 'Carpentry & Joinery', TRUE),
  ('MAT-INTERN', 'Internal door blank', 'each', 68, 'Carpentry & Joinery', TRUE),
  ('MAT-DOORLI', 'Door lining set', 'each', 36, 'Carpentry & Joinery', TRUE),
  ('MAT-IRONMO', 'Ironmongery set', 'set', 24, 'Carpentry & Joinery', TRUE),
  ('MAT-WOODSC', 'Wood screws assorted', 'box', 12, 'Carpentry & Joinery', TRUE),
  ('MAT-PUWOOD', 'PU wood adhesive', 'tube', 6.5, 'Carpentry & Joinery', TRUE),
  ('MAT-EXPAND', 'Expanding foam', 'can', 5.5, 'Carpentry & Joinery', TRUE),
  ('MAT-JOISTH', 'Joist hanger', 'each', 1.25, 'Carpentry & Joinery', TRUE),
  ('MAT-DECKIN', 'Decking board treated', 'm', 5.2, 'Carpentry & Joinery', TRUE),
  ('MAT-TWINAN', 'Twin and earth cable 1.5mm²', 'm', 0.85, 'Electrical', TRUE),
  ('MAT-TWINAN2', 'Twin and earth cable 2.5mm²', 'm', 1.25, 'Electrical', TRUE),
  ('MAT-SWACAB', 'SWA cable 3 core 2.5mm²', 'm', 2.95, 'Electrical', TRUE),
  ('MAT-PVCCON', 'PVC conduit 20mm', 'm', 1.15, 'Electrical', TRUE),
  ('MAT-GALVAN', 'Galvanised trunking', 'm', 8.5, 'Electrical', TRUE),
  ('MAT-BACKBO', 'Back box 25mm', 'each', 1.2, 'Electrical', TRUE),
  ('MAT-DOUBLE', 'Double socket outlet', 'each', 4.8, 'Electrical', TRUE),
  ('MAT-LIGHTS', 'Light switch 1 gang', 'each', 3.2, 'Electrical', TRUE),
  ('MAT-LEDDOW', 'LED downlight', 'each', 11.5, 'Electrical', TRUE),
  ('MAT-CONSUM', 'Consumer unit', 'each', 95, 'Electrical', TRUE),
  ('MAT-RCBO', 'RCBO', 'each', 14.5, 'Electrical', TRUE),
  ('MAT-MCB', 'MCB', 'each', 6.8, 'Electrical', TRUE),
  ('MAT-CABLEC', 'Cable clips assorted', 'pack', 4.5, 'Electrical', TRUE),
  ('MAT-CABLET', 'Cable tray', 'm', 7.5, 'Electrical', TRUE),
  ('MAT-EARTHR', 'Earth rod', 'each', 12.5, 'Electrical', TRUE),
  ('MAT-COPPER', 'Copper tube 15mm', 'm', 5.5, 'Plumbing & Mechanical', TRUE),
  ('MAT-COPPER2', 'Copper tube 22mm', 'm', 8.8, 'Plumbing & Mechanical', TRUE),
  ('MAT-PEXPIP', 'PEX pipe 15mm', 'm', 1.2, 'Plumbing & Mechanical', TRUE),
  ('MAT-WASTEP', 'Waste pipe 40mm', 'm', 2.6, 'Plumbing & Mechanical', TRUE),
  ('MAT-WASTEP2', 'Waste pipe 110mm', 'm', 5.8, 'Plumbing & Mechanical', TRUE),
  ('MAT-LEVERB', 'Lever basin tap', 'each', 48, 'Plumbing & Mechanical', TRUE),
  ('MAT-WCCLOS', 'WC close-coupled suite', 'each', 165, 'Plumbing & Mechanical', TRUE),
  ('MAT-BASIN', 'Basin', 'each', 68, 'Plumbing & Mechanical', TRUE),
  ('MAT-BATHAC', 'Bath acrylic', 'each', 185, 'Plumbing & Mechanical', TRUE),
  ('MAT-SHOWER', 'Shower valve', 'each', 95, 'Plumbing & Mechanical', TRUE),
  ('MAT-RADIAT', 'Radiator double panel', 'each', 72, 'Plumbing & Mechanical', TRUE),
  ('MAT-TRVVAL', 'TRV valve set', 'pair', 18, 'Plumbing & Mechanical', TRUE),
  ('MAT-CONDEN', 'Condensing boiler', 'each', 980, 'Plumbing & Mechanical', TRUE),
  ('MAT-MAGNET', 'Magnetic filter', 'each', 82, 'Plumbing & Mechanical', TRUE),
  ('MAT-PIPEIN', 'Pipe insulation 15mm', 'm', 1.1, 'Plumbing & Mechanical', TRUE),
  ('MAT-SOLVEN', 'Solvent cement', 'tin', 6.8, 'Plumbing & Mechanical', TRUE),
  ('MAT-PLASTE', 'Plasterboard 12.5mm', 'sheet', 12.5, 'Plastering & Drylining', TRUE),
  ('MAT-MOISTU', 'Moisture resistant plasterboard 12.5mm', 'sheet', 16.5, 'Plastering & Drylining', TRUE),
  ('MAT-FIRELI', 'Fireline plasterboard 15mm', 'sheet', 21, 'Plastering & Drylining', TRUE),
  ('MAT-SOUNDB', 'Soundbloc plasterboard', 'sheet', 18.5, 'Plastering & Drylining', TRUE),
  ('MAT-METALS', 'Metal stud 70mm', 'm', 3.4, 'Plastering & Drylining', TRUE),
  ('MAT-METALT', 'Metal track 70mm', 'm', 2.6, 'Plastering & Drylining', TRUE),
  ('MAT-ANGLEB', 'Angle bead', 'm', 0.95, 'Plastering & Drylining', TRUE),
  ('MAT-JOINTT', 'Joint tape', 'roll', 3.8, 'Plastering & Drylining', TRUE),
  ('MAT-JOINTF', 'Joint filler', 'bag', 15.5, 'Plastering & Drylining', TRUE),
  ('MAT-MULTIF', 'Multi-finish plaster', 'bag', 11.8, 'Plastering & Drylining', TRUE),
  ('MAT-BONDIN', 'Bonding plaster', 'bag', 10.5, 'Plastering & Drylining', TRUE),
  ('MAT-PLASTE2', 'Plasterboard screws', 'box', 9.5, 'Plastering & Drylining', TRUE),
  ('MAT-ACOUST', 'Acoustic insulation slab', 'm²', 7.8, 'Plastering & Drylining', TRUE),
  ('MAT-RESILI', 'Resilient bar', 'm', 2.4, 'Plastering & Drylining', TRUE),
  ('MAT-ACCESS', 'Access panel', 'each', 28, 'Plastering & Drylining', TRUE),
  ('MAT-TRADEE', 'Trade emulsion paint', 'litre', 4.8, 'Painting & Decorating', TRUE),
  ('MAT-ACRYLI', 'Acrylic eggshell', 'litre', 8.2, 'Painting & Decorating', TRUE),
  ('MAT-SATINW', 'Satinwood paint', 'litre', 9.2, 'Painting & Decorating', TRUE),
  ('MAT-GLOSSP', 'Gloss paint', 'litre', 8.5, 'Painting & Decorating', TRUE),
  ('MAT-MASONR2', 'Masonry paint', 'litre', 6.8, 'Painting & Decorating', TRUE),
  ('MAT-PRIMER', 'Primer undercoat', 'litre', 7.2, 'Painting & Decorating', TRUE),
  ('MAT-STAINB', 'Stain block', 'litre', 12.5, 'Painting & Decorating', TRUE),
  ('MAT-FILLER', 'Filler', 'tube', 3.8, 'Painting & Decorating', TRUE),
  ('MAT-CAULK', 'Caulk', 'tube', 2.2, 'Painting & Decorating', TRUE),
  ('MAT-SANDPA', 'Sandpaper assorted', 'pack', 6.5, 'Painting & Decorating', TRUE),
  ('MAT-MASKIN', 'Masking tape', 'roll', 2.5, 'Painting & Decorating', TRUE),
  ('MAT-WALLPA', 'Wallpaper', 'roll', 18, 'Painting & Decorating', TRUE),
  ('MAT-WALLPA2', 'Wallpaper adhesive', 'bag', 5.5, 'Painting & Decorating', TRUE),
  ('MAT-DUSTSH', 'Dust sheet polythene', 'roll', 16, 'Painting & Decorating', TRUE),
  ('MAT-CONCRE5', 'Concrete roof tile', 'each', 1.15, 'Roofing', TRUE),
  ('MAT-NATURA2', 'Natural slate', 'each', 1.9, 'Roofing', TRUE),
  ('MAT-BREATH', 'Breather membrane', 'm²', 1.8, 'Roofing', TRUE),
  ('MAT-ROOFIN', 'Roofing battens', 'm', 1.25, 'Roofing', TRUE),
  ('MAT-LEADFL', 'Lead flashing code 4', 'm', 18.5, 'Roofing', TRUE),
  ('MAT-LEADFL2', 'Lead flashing code 5', 'm', 23.5, 'Roofing', TRUE),
  ('MAT-RIDGET', 'Ridge tile', 'each', 7.5, 'Roofing', TRUE),
  ('MAT-DRYRID', 'Dry ridge system', 'm', 9.5, 'Roofing', TRUE),
  ('MAT-DRYVER', 'Dry verge system', 'm', 8.5, 'Roofing', TRUE),
  ('MAT-EPDMME', 'EPDM membrane', 'm²', 14.5, 'Roofing', TRUE),
  ('MAT-SINGLE', 'Single ply membrane', 'm²', 18, 'Roofing', TRUE),
  ('MAT-ROOFIN2', 'Roof insulation board', 'm²', 16.5, 'Roofing', TRUE),
  ('MAT-FELTUN', 'Felt underlay', 'm²', 2.2, 'Roofing', TRUE),
  ('MAT-GUTTER', 'Gutter 112mm uPVC', 'm', 5.8, 'Roofing', TRUE),
  ('MAT-DOWNPI', 'Downpipe 68mm uPVC', 'm', 4.5, 'Roofing', TRUE),
  ('MAT-TOPSOI2', 'Topsoil screened', 'm³', 42, 'Landscaping & External Works', TRUE),
  ('MAT-COMPOS', 'Compost', 'm³', 58, 'Landscaping & External Works', TRUE),
  ('MAT-TURF', 'Turf', 'm²', 4.8, 'Landscaping & External Works', TRUE),
  ('MAT-GRASSS', 'Grass seed', 'kg', 8.5, 'Landscaping & External Works', TRUE),
  ('MAT-DECORA', 'Decorative gravel', 'tonne', 78, 'Landscaping & External Works', TRUE),
  ('MAT-RAILWA', 'Railway sleeper', 'each', 28, 'Landscaping & External Works', TRUE),
  ('MAT-FENCEP', 'Fence panel', 'each', 38, 'Landscaping & External Works', TRUE),
  ('MAT-CONCRE6', 'Concrete fence post', 'each', 22, 'Landscaping & External Works', TRUE),
  ('MAT-GRAVEL', 'Gravel board', 'each', 16, 'Landscaping & External Works', TRUE),
  ('MAT-TIMBER2', 'Timber fence post', 'each', 14, 'Landscaping & External Works', TRUE),
  ('MAT-WEEDCO', 'Weed control membrane', 'm²', 1.3, 'Landscaping & External Works', TRUE),
  ('MAT-BARKMU', 'Bark mulch', 'm³', 52, 'Landscaping & External Works', TRUE),
  ('MAT-COMPOS2', 'Composite decking board', 'm', 12.5, 'Landscaping & External Works', TRUE),
  ('MAT-TIMBER3', 'Timber decking joist', 'm', 4.2, 'Landscaping & External Works', TRUE),
  ('MAT-PERGOL', 'Pergola timber post', 'each', 24, 'Landscaping & External Works', TRUE),
  ('MAT-UNIVER', 'Universal beam', 'kg', 1.95, 'Steel & Structural', TRUE),
  ('MAT-UNIVER2', 'Universal column', 'kg', 1.95, 'Steel & Structural', TRUE),
  ('MAT-PARALL', 'Parallel flange channel', 'kg', 1.98, 'Steel & Structural', TRUE),
  ('MAT-ANGLES', 'Angle section', 'kg', 2.05, 'Steel & Structural', TRUE),
  ('MAT-HOLLOW', 'Hollow section RHS', 'kg', 2.15, 'Steel & Structural', TRUE),
  ('MAT-BASEPL', 'Base plate fabricated', 'kg', 2.45, 'Steel & Structural', TRUE),
  ('MAT-CLEATP', 'Cleat plate', 'kg', 2.3, 'Steel & Structural', TRUE),
  ('MAT-HOLDIN', 'Holding down bolts', 'set', 18, 'Steel & Structural', TRUE),
  ('MAT-CHEMIC', 'Chemical anchor resin', 'tube', 16, 'Steel & Structural', TRUE),
  ('MAT-HIGHST', 'High strength bolts', 'each', 1.8, 'Steel & Structural', TRUE),
  ('MAT-PACKER', 'Packers and shims', 'pack', 12, 'Steel & Structural', TRUE),
  ('MAT-INTUME', 'Intumescent coating', 'litre', 18, 'Steel & Structural', TRUE),
  ('MAT-TOUCHU', 'Touch-up galvanising paint', 'can', 12, 'Steel & Structural', TRUE),
  ('MAT-STEELP', 'Steel primer', 'litre', 9.8, 'Steel & Structural', TRUE),
  ('MAT-POLYTH', 'Polythene sheeting', 'roll', 22, 'Demolition & Strip Out', TRUE),
  ('MAT-DEBRIS', 'Debris bags', 'pack', 8.5, 'Demolition & Strip Out', TRUE),
  ('MAT-DUSTBA', 'Dust barrier zip kit', 'set', 18, 'Demolition & Strip Out', TRUE),
  ('MAT-TIMBER4', 'Timber hoarding sheet', 'sheet', 22, 'Demolition & Strip Out', TRUE),
  ('MAT-HERASF', 'Heras fence panel', 'each', 28, 'Demolition & Strip Out', TRUE),
  ('MAT-HERASF2', 'Heras fence block', 'each', 10, 'Demolition & Strip Out', TRUE),
  ('MAT-WARNIN2', 'Warning signage', 'each', 9, 'Demolition & Strip Out', TRUE),
  ('MAT-PROTEC', 'Protection board', 'sheet', 18, 'Demolition & Strip Out', TRUE),
  ('MAT-ASBEST', 'Asbestos warning labels', 'pack', 6, 'Demolition & Strip Out', TRUE),
  ('MAT-SUSPEN', 'Suspended ceiling grid', 'm²', 8.5, 'Fit-Out & Finishes', TRUE),
  ('MAT-MINERA', 'Mineral fibre ceiling tile', 'm²', 9.8, 'Fit-Out & Finishes', TRUE),
  ('MAT-MFCEIL', 'MF ceiling components', 'm²', 7.8, 'Fit-Out & Finishes', TRUE),
  ('MAT-PARTIT', 'Partition head track', 'm', 2.6, 'Fit-Out & Finishes', TRUE),
  ('MAT-PARTIT2', 'Partition studs', 'm', 3.4, 'Fit-Out & Finishes', TRUE),
  ('MAT-PLYWOO2', 'Plywood 12mm', 'sheet', 24, 'Fit-Out & Finishes', TRUE),
  ('MAT-MDFSKI', 'MDF skirting', 'm', 4.2, 'Fit-Out & Finishes', TRUE),
  ('MAT-DOORIR', 'Door ironmongery set', 'set', 24, 'Fit-Out & Finishes', TRUE),
  ('MAT-VISION', 'Vision panel glazing', 'm²', 68, 'Fit-Out & Finishes', TRUE),
  ('MAT-ACOUST2', 'Acoustic sealant', 'tube', 4.2, 'Fit-Out & Finishes', TRUE),
  ('MAT-SILICO', 'Silicone sealant', 'tube', 3.5, 'Fit-Out & Finishes', TRUE),
  ('MAT-WALLPR', 'Wall protection board', 'sheet', 26, 'Fit-Out & Finishes', TRUE),
  ('MAT-LAMINA', 'Laminate worktop', 'm', 42, 'Fit-Out & Finishes', TRUE),
  ('MAT-IPSPAN', 'IPS panel', 'm²', 58, 'Fit-Out & Finishes', TRUE),
  ('MAT-CERAMI', 'Ceramic wall tile', 'm²', 18, 'Tiling & Flooring', TRUE),
  ('MAT-PORCEL2', 'Porcelain tile', 'm²', 28, 'Tiling & Flooring', TRUE),
  ('MAT-NATURA3', 'Natural stone tile', 'm²', 42, 'Tiling & Flooring', TRUE),
  ('MAT-TILEAD', 'Tile adhesive', 'bag', 14.5, 'Tiling & Flooring', TRUE),
  ('MAT-TILEGR', 'Tile grout', 'bag', 9.5, 'Tiling & Flooring', TRUE),
  ('MAT-TILETR', 'Tile trim', 'm', 3.2, 'Tiling & Flooring', TRUE),
  ('MAT-SELFLE', 'Self-levelling compound', 'bag', 17.5, 'Tiling & Flooring', TRUE),
  ('MAT-FLOORP', 'Floor primer', 'litre', 4.8, 'Tiling & Flooring', TRUE),
  ('MAT-SHEETV', 'Sheet vinyl', 'm²', 16, 'Tiling & Flooring', TRUE),
  ('MAT-LVTFLO', 'LVT flooring', 'm²', 24, 'Tiling & Flooring', TRUE),
  ('MAT-LAMINA2', 'Laminate flooring', 'm²', 14, 'Tiling & Flooring', TRUE),
  ('MAT-ENGINE2', 'Engineered timber flooring', 'm²', 32, 'Tiling & Flooring', TRUE),
  ('MAT-CARPET', 'Carpet tile', 'm²', 18, 'Tiling & Flooring', TRUE),
  ('MAT-FLOORI', 'Flooring underlay', 'm²', 3.8, 'Tiling & Flooring', TRUE),
  ('MAT-DPMLIQ', 'DPM liquid membrane', 'm²', 5.5, 'Tiling & Flooring', TRUE),
  ('MAT-UPVCWI', 'uPVC window', 'each', 265, 'Glazing & Windows/Doors', TRUE),
  ('MAT-ALUMIN', 'Aluminium window', 'm²', 285, 'Glazing & Windows/Doors', TRUE),
  ('MAT-COMPOS3', 'Composite front door set', 'each', 1250, 'Glazing & Windows/Doors', TRUE),
  ('MAT-UPVCPA', 'uPVC patio door set', 'each', 880, 'Glazing & Windows/Doors', TRUE),
  ('MAT-DOUBLE2', 'Double glazed unit', 'm²', 75, 'Glazing & Windows/Doors', TRUE),
  ('MAT-TOUGHE', 'Toughened glass', 'm²', 98, 'Glazing & Windows/Doors', TRUE),
  ('MAT-LAMINA3', 'Laminated glass', 'm²', 110, 'Glazing & Windows/Doors', TRUE),
  ('MAT-WINDOW', 'Window board', 'm', 6.8, 'Glazing & Windows/Doors', TRUE),
  ('MAT-FRAMEF', 'Frame fixings', 'pack', 8.5, 'Glazing & Windows/Doors', TRUE),
  ('MAT-LOWMOD', 'Low modulus silicone', 'tube', 4.2, 'Glazing & Windows/Doors', TRUE),
  ('MAT-EPDMTA', 'EPDM tape', 'roll', 16.5, 'Glazing & Windows/Doors', TRUE),
  ('MAT-PACKER2', 'Packers assorted', 'pack', 4.8, 'Glazing & Windows/Doors', TRUE),
  ('MAT-TRICKL', 'Trickle vent', 'each', 8.5, 'Glazing & Windows/Doors', TRUE),
  ('MAT-MINERA2', 'Mineral wool insulation', 'm²', 5.8, 'Insulation & Damp Proofing', TRUE),
  ('MAT-PIRINS', 'PIR insulation board 50mm', 'm²', 12.5, 'Insulation & Damp Proofing', TRUE),
  ('MAT-PIRINS2', 'PIR insulation board 100mm', 'm²', 21, 'Insulation & Damp Proofing', TRUE),
  ('MAT-ACOUST3', 'Acoustic slab insulation', 'm²', 7.8, 'Insulation & Damp Proofing', TRUE),
  ('MAT-LOFTRO', 'Loft roll insulation', 'm²', 4.2, 'Insulation & Damp Proofing', TRUE),
  ('MAT-VAPOUR', 'Vapour control layer', 'm²', 1.9, 'Insulation & Damp Proofing', TRUE),
  ('MAT-CAVITY2', 'Cavity wall insulation bead', 'bag', 18, 'Insulation & Damp Proofing', TRUE),
  ('MAT-DPCCRE', 'DPC cream', 'tube', 16.5, 'Insulation & Damp Proofing', TRUE),
  ('MAT-TANKIN', 'Tanking slurry', 'bag', 26, 'Insulation & Damp Proofing', TRUE),
  ('MAT-WATERP', 'Waterproof membrane', 'm²', 7.5, 'Insulation & Damp Proofing', TRUE),
  ('MAT-FOILTA', 'Foil tape', 'roll', 7.5, 'Insulation & Damp Proofing', TRUE),
  ('MAT-INSULA', 'Insulation fixings', 'pack', 14, 'Insulation & Damp Proofing', TRUE),
  ('MAT-BASECA', 'Base cabinet', 'each', 68, 'Kitchen & Bathroom Installation', TRUE),
  ('MAT-WALLCA', 'Wall cabinet', 'each', 58, 'Kitchen & Bathroom Installation', TRUE),
  ('MAT-TALLLA', 'Tall larder unit', 'each', 145, 'Kitchen & Bathroom Installation', TRUE),
  ('MAT-SOLIDS', 'Solid surface worktop', 'm', 185, 'Kitchen & Bathroom Installation', TRUE),
  ('MAT-SINKAN', 'Sink and drainer', 'each', 88, 'Kitchen & Bathroom Installation', TRUE),
  ('MAT-MONOBL', 'Monobloc kitchen tap', 'each', 58, 'Kitchen & Bathroom Installation', TRUE),
  ('MAT-SHOWER2', 'Shower tray', 'each', 98, 'Kitchen & Bathroom Installation', TRUE),
  ('MAT-SHOWER3', 'Shower screen', 'each', 118, 'Kitchen & Bathroom Installation', TRUE),
  ('MAT-VANITY', 'Vanity unit', 'each', 145, 'Kitchen & Bathroom Installation', TRUE),
  ('MAT-WCPANA', 'WC pan and cistern', 'each', 165, 'Kitchen & Bathroom Installation', TRUE),
  ('MAT-SCAFFO', 'Scaffold tube 48.3mm', 'm', 4.2, 'Scaffolding & Access', TRUE),
  ('MAT-SCAFFO2', 'Scaffold board', 'm', 4.8, 'Scaffolding & Access', TRUE),
  ('MAT-DOUBLE3', 'Double coupler', 'each', 1.9, 'Scaffolding & Access', TRUE),
  ('MAT-SWIVEL', 'Swivel coupler', 'each', 2.4, 'Scaffolding & Access', TRUE),
  ('MAT-BASEPL2', 'Base plate', 'each', 3.2, 'Scaffolding & Access', TRUE),
  ('MAT-SOLEBO', 'Sole board', 'each', 4.5, 'Scaffolding & Access', TRUE),
  ('MAT-TOEBOA', 'Toe board', 'm', 2.8, 'Scaffolding & Access', TRUE),
  ('MAT-DEBRIS2', 'Debris netting', 'm²', 1.2, 'Scaffolding & Access', TRUE),
  ('MAT-MONARF', 'Monarflex sheeting', 'm²', 2.5, 'Scaffolding & Access', TRUE),
  ('MAT-LADDER', 'Ladder access gate', 'each', 36, 'Scaffolding & Access', TRUE),
  ('MAT-BRICKG', 'Brick guard', 'each', 8.5, 'Scaffolding & Access', TRUE),
  ('MAT-TIEANC', 'Tie anchor', 'each', 2.8, 'Scaffolding & Access', TRUE),
  ('MAT-PEDEST', 'Pedestrian barrier', 'each', 18, 'Waste Management & Site Setup', TRUE),
  ('MAT-SITESI', 'Site signage', 'each', 9, 'Waste Management & Site Setup', TRUE),
  ('MAT-PLYWOO3', 'Plywood hoarding sheet', 'sheet', 22, 'Waste Management & Site Setup', TRUE),
  ('MAT-TEMPOR', 'Temporary lighting string', 'm', 4.2, 'Waste Management & Site Setup', TRUE),
  ('MAT-EXTENS', 'Extension lead 110v', 'each', 24, 'Waste Management & Site Setup', TRUE),
  ('MAT-FUELFO', 'Fuel for generator', 'litre', 1.45, 'Waste Management & Site Setup', TRUE),
  ('MAT-CABLER', 'Cable ramp', 'each', 42, 'Waste Management & Site Setup', TRUE) ON CONFLICT DO NOTHING;

-- Done